import { useMemo } from "react";
import "./AldreteScore.css";

export default function AldreteScore({ patientName, patientData }) {
  const name = patientName;

  const { dateTimeStr, generatedOn } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const h = now.getHours();
    const m = now.getMinutes();
    const hh = String(h % 12 || 12).padStart(2, "0");
    const ampm = h < 12 ? "am" : "pm";
    const AMPM = h < 12 ? "AM" : "PM";

    const dateStr = now.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
    const timeStr = `${hh}:${pad(m)} ${AMPM}`;
    const dateTimeStr = `Date: ${dateStr} Time: ${timeStr}`;
    const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(m)} ${ampm}`;
    return { dateTimeStr, generatedOn };
  }, []);

  const categories = [
    {
      name: "COLOR",
      items: [
        { label: "Pink", value: 2 },
        { label: "Pale/dusky", value: 1 },
        { label: "Cyanotic", value: 0 },
      ],
    },
    {
      name: "RESPIRATION",
      items: [
        { label: "Can breathe deeply", value: 2 },
        { label: "Shallow but adequate", value: 1 },
        { label: "Apnea or obstruction", value: 0 },
      ],
    },
    {
      name: "CIRCULATION",
      items: [
        { label: "Bp within 20% of normal", value: 2 },
        { label: "Bp within 21-50% of normal", value: 1 },
        { label: "Bp within >50% of normal", value: 0 },
      ],
    },
    {
      name: "CONSCIOUSNESS",
      items: [
        { label: "Awake, alert and oriented", value: 2 },
        { label: "Arousable but readily back to sleep", value: 1 },
        { label: "No response", value: 0 },
      ],
    },
    {
      name: "ACTIVITY",
      items: [
        { label: "Moves all extremities", value: 2 },
        { label: "Moves two extremities", value: 1 },
        { label: "No movement", value: 0 },
      ],
    },
  ];

  return (
    <div className="ald-page">

      {/* ── Header ── */}
      <div className="ald-header">
        <div className="ald-header-grid">
          <div className="ald-header-cell">
            <span className="ald-bold">Case Number:</span>&nbsp;ADM-2026-010707
          </div>
          <div className="ald-header-cell">
            <span className="ald-bold">Age:</span>&nbsp;32 year(s)
          </div>
          <div className="ald-header-cell">
            <span className="ald-bold">Name of Patient:</span>&nbsp;{name}
          </div>
          <div className="ald-header-cell">
            <span className="ald-bold">Sex:</span>&nbsp;F
          </div>
          <div className="ald-header-cell ald-header-cell--full">
            <span className="ald-bold">ROOM:</span>&nbsp;OB GYNE - POST-OP OB - BED 07
          </div>
        </div>
      </div>

      {/* ── Discharge note ── */}
      <div className="ald-note">*Patient discharged when the score is 10</div>

      {/* ── Score table ── */}
      <table className="ald-table">
        <thead>
          <tr>
            <th style={{ textAlign: "left", width: "80%" }}></th>
            <th style={{ textAlign: "center", width: "20%" }}>Point Value</th>
          </tr>
        </thead>
        <tbody>
          {categories.map((cat, ci) => (
            <>
              {/* Category header row */}
              <tr key={`cat-${ci}`} className="ald-cat-row">
                <td colSpan={2}>{cat.name}</td>
              </tr>
              {/* Item rows */}
              {cat.items.map((item, ii) => (
                <tr key={`item-${ci}-${ii}`} className="ald-item-row">
                  <td>{item.label}</td>
                  <td>{item.value}</td>
                </tr>
              ))}
            </>
          ))}
          {/* Total row */}
          <tr className="ald-total-row">
            <td>Total</td>
            <td></td>
          </tr>
        </tbody>
      </table>

      {/* ── Signature ── */}
      <br />
      <div className="ald-sig-section">
        <div className="ald-sig-block">
          <div className="ald-sig-line" />
          <div className="ald-sig-label">Signature over Printed Name of PACU Nurse</div>
          <div className="ald-sig-date">{dateTimeStr}</div>
        </div>
      </div>

      {/* ── Footer ── */}
      <div className="ald-footer">
        Generated by: TCP T. TCP on {generatedOn}
      </div>

    </div>
  );
}