import "./ApgarScoring.css";

export default function ApgarScoring() {
  return (
    <div className="a4-page">

      {/* Header replaced with spacer */}
      <div className="header-spacer" />

      {/* Form meta */}
      <div className="form-meta">
        FORM NO.: ___________<br />
        Revised: ___________
      </div>

      {/* Title */}
      <div className="form-title">APGAR SCORING</div>

      {/* Case Number */}
      <div className="case-number-row">
        <strong>Case Number:</strong>&nbsp; ADM-2026-010617
      </div>

      {/* Patient Info Table */}
      <table className="info-table">
        <tbody>
          <tr>
            <td className="lbl">Baby's Name:</td>
            <td style={{ width: "42%" }}></td>
            <td className="lbl">Sex:</td>
            <td style={{ width: "8%", textAlign: "center" }}>F</td>
            <td className="lbl">Age:</td>
            <td style={{ width: "12%", textAlign: "center" }}>67 year(s)</td>
          </tr>
          <tr>
            <td className="lbl">Mother's Name:</td>
            <td style={{ textAlign: "center" }}>Error: No newborn record found.</td>
            <td className="lbl">Sex:</td>
            <td
              colSpan={3}
              style={{ fontSize: "8pt", textAlign: "center", lineHeight: 1.4 }}
            >
              Error: No<br />newborn<br />record<br />found.
            </td>
          </tr>
          <tr>
            <td className="lbl">Hospital No.</td>
            <td style={{ textAlign: "center" }}>000000000020971</td>
            <td className="lbl">Complete Address:</td>
            <td colSpan={3} style={{ textAlign: "center" }}>
              P-1, ALUBJID, BUENAVISTA, AGUSAN DEL NORTE
            </td>
          </tr>
          <tr>
            <td className="lbl">Type of Delivery:</td>
            <td></td>
            <td className="lbl">Obstetrician:</td>
            <td colSpan={3}></td>
          </tr>
          <tr>
            <td className="lbl">Anesthesia:</td>
            <td></td>
            <td className="lbl">Anesthesiologist:</td>
            <td colSpan={3}></td>
          </tr>
        </tbody>
      </table>

      {/* Sign Reference Table */}
      <table className="sign-table">
        <thead>
          <tr>
            <th style={{ width: "18%" }}>SIGN</th>
            <th style={{ width: "18%" }}>0</th>
            <th style={{ width: "34%" }}>1</th>
            <th style={{ width: "30%" }}>2</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Appearance</td>
            <td>Blue or pale</td>
            <td>Blue extremities, but torso is pink</td>
            <td>Completely pink</td>
          </tr>
          <tr>
            <td>Pulse</td>
            <td>Absent</td>
            <td>&lt;100</td>
            <td>&gt;100</td>
          </tr>
          <tr>
            <td>Grimace</td>
            <td>No response</td>
            <td>Weak grimace when stimulated</td>
            <td>Cries or pulls away when stimulated</td>
          </tr>
          <tr>
            <td>Activity</td>
            <td>None</td>
            <td>Some flexion of arms</td>
            <td>Arms flexed, legs resist extension</td>
          </tr>
          <tr>
            <td>Respiration</td>
            <td>Absent</td>
            <td>Weak, irregular or gasping</td>
            <td>Strong cry</td>
          </tr>
        </tbody>
      </table>

      {/* APGAR Scoring Table */}
      <table className="score-table">
        <thead>
          <tr>
            <th style={{ width: "25%" }}>APGAR</th>
            <th style={{ width: "25%" }}>1 MINUTE</th>
            <th style={{ width: "25%" }}>5 MINUTES</th>
            <th style={{ width: "25%" }}>10 MINUTES</th>
          </tr>
        </thead>
        <tbody>
          {["Appearance", "Pulse", "Grimace", "Activity", "Respiration"].map((sign) => (
            <tr key={sign}>
              <td>{sign}</td>
              <td className="blank-cell"></td>
              <td className="blank-cell"></td>
              <td className="blank-cell"></td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Signature Footer */}
      <div className="footer-sig">
        <div className="sig-line" />
        <div className="sig-label">PEDIATRICIAN</div>
      </div>

      {/* Generated By */}
      <div className="generated-by">
        <em>Generated by: TCP T. TCP on 2026-04-21 11:11 am</em>
      </div>

    </div>
  );
}