import "./BallardScore.css";

const formatGeneratedOn = (date = new Date()) => {
  const pad = (v) => String(v).padStart(2, "0");
  const h    = date.getHours();
  const m    = date.getMinutes();
  const ampm = h >= 12 ? "pm" : "am";
  const h12  = String(h % 12 || 12).padStart(2, "0");
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${h12}:${pad(m)} ${ampm}`;
};

export default function BallardScore({ patientName, patientData = {} }) {
  const chartSrc   = "src/modules/forms/img/ballard.png";
  const caseNum    = patientData.caseNum    || patientData.caseNo     || "";
  const name       = patientName            || patientData.patientName || patientData.fullName || "";
  const hospitalNo = patientData.hospitalNo || patientData.hospNo     || patientData.hospitalNumber || "";
  const birthDate  = patientData.birthDate  || patientData.birthdate  || patientData.dob || "";
  const birthTime  = patientData.birthTime  || "";
  const generatedOn = patientData.generatedOn || formatGeneratedOn();

  return (
    <div className="ballard-page-wrap">
      <br />
      <div className="ballard-page">
        <div className="ballard-content">

          {/* ── Patient Info ── */}
          <div className="ballard-info-section">
            <br />
            <div className="ballard-case-number">
              <span className="ballard-label">Case Number:</span>
              <span className="ballard-value">{caseNum}</span>
            </div>

            <table className="ballard-info-table">
              <tbody>
                <tr>
                  <td className="ballard-cell-label">Name of Patient:</td>
                  <td className="ballard-cell-value">{name}</td>
                  <td className="ballard-cell-label">Hospital No.:</td>
                  <td className="ballard-cell-value">{hospitalNo}</td>
                </tr>
                <tr>
                  <td className="ballard-cell-label">Date of Birth:</td>
                  <td className="ballard-cell-value">{birthDate}</td>
                  <td className="ballard-cell-label">Time of Birth:</td>
                  <td className="ballard-cell-value">{birthTime}</td>
                </tr>
              </tbody>
            </table>
          </div>

          {/* ── Chart ── */}
          <div className="ballard-main">
            <div className="ballard-chart-wrap">
              <img
                className="ballard-chart"
                src={chartSrc}
                alt="Ballard scoring chart"
              />
            </div>
          </div>
          <br />
          <br />

          {/* ── Pediatrician signature ── */}
          <div className="ballard-signature-wrap">
            <div className="ballard-signature">
              <div className="ballard-sign-line" />
              <div className="ballard-sign-label">PEDIATRICIAN</div>
            </div>
          </div>

        </div>{/* end .ballard-content */}

        {/* ── Footer — same pattern as .abtr-footer ── */}
        <div className="ballard-footer">
          Generated by: TCP T. TCP on {generatedOn}
        </div>

      </div>{/* end .ballard-page */}
    </div>
  );
}