import "./BallardScore.css";

const formatGeneratedOn = (date = new Date()) => {
  const pad = (value) => String(value).padStart(2, "0");
  const hours = date.getHours();
  const minutes = date.getMinutes();
  const ampm = hours >= 12 ? "pm" : "am";
  const hour12 = String(hours % 12 || 12).padStart(2, "0");

  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${hour12}:${pad(minutes)} ${ampm}`;
};

export default function BallardScore({ patientName, patientData = {} }) {
	const chartSrc = "src/modules/forms/img/ballard.png";
  const caseNum = patientData.caseNum || patientData.caseNo || "";
  const name = patientName || patientData.patientName || patientData.fullName || "";
  const hospitalNo =
    patientData.hospitalNo || patientData.hospNo || patientData.hospitalNumber || "";
  const birthDate =
    patientData.birthDate || patientData.birthdate || patientData.dob || "";
  const birthTime = patientData.birthTime || "";
  const generatedOn = patientData.generatedOn || formatGeneratedOn();

	return (
		<div className="ballard-page-wrap">
			<div className="ballard-page">
				<div className="ballard-content">
				
                        <div className="ballard-info-section">
                        <div className="ballard-case-number">
                            <span className="ballard-label">Case Number:</span>
                          <span className="ballard-value">{caseNum}</span>
                        </div>

                        <table className="ballard-info-table">
                            <tbody>
                            <tr>
                                <td className="ballard-cell-label">Name of Patient:</td>
                                <td className="ballard-cell-value">{name}</td>
                                <td className="ballard-cell-label">Hospital No.:</td>
                                <td className="ballard-cell-value">{hospitalNo}</td>
                            </tr>
                            <tr>
                                <td className="ballard-cell-label">Date of Birth:</td>
                                <td className="ballard-cell-value">{birthDate}</td>
                                <td className="ballard-cell-label">Time of Birth:</td>
                                <td className="ballard-cell-value">{birthTime}</td>
                            </tr>
                            </tbody>
                        </table>
                        </div>

				<div className="ballard-main">
					<div className="ballard-chart-wrap">
						<img
							className="ballard-chart"
							src={chartSrc}
							alt="Ballard scoring chart"
						/>
					</div>

					
                    </div>
                  <div className="ballard-footer">
  <div className="ballard-signature">
    <div className="ballard-sign-line" />
    <div className="ballard-sign-label">PEDIATRICIAN</div>
  </div>
  
  <div className="ballard-default-footer">
    <div className="ballard-generated-line" />
    <div className="ballard-generated">Generated by: TCP T. TCP on {generatedOn}</div>
  </div>
</div>
				</div>
			</div>
		</div>
	);
}
