import "./BallardScore.css";

export default function BallardScore() {
	const chartSrc = "src/modules/forms/img/ballard.png";

	return (
		<div className="ballard-page-wrap">
			<div className="ballard-page">
				<div className="ballard-content">
				
                        <div className="ballard-info-section">
                        <div className="ballard-case-number">
                            <span className="ballard-label">Case Number:</span>
                            <span className="ballard-value">ADM-2026-010651</span>
                        </div>

                        <table className="ballard-info-table">
                            <tbody>
                            <tr>
                                <td className="ballard-cell-label">Name of Patient:</td>
                                <td className="ballard-cell-value">FELISELDA , CIAN REIN BAYSA</td>
                                <td className="ballard-cell-label">Hospital No.:</td>
                                <td className="ballard-cell-value">000000000021041</td>
                            </tr>
                            <tr>
                                <td className="ballard-cell-label">Date of Birth:</td>
                                <td className="ballard-cell-value">April 22, 2026</td>
                                <td className="ballard-cell-label">Time of Birth:</td>
                                <td className="ballard-cell-value">04:10 AM</td>
                            </tr>
                            </tbody>
                        </table>
                        </div>

				<div className="ballard-main">
					<div className="ballard-chart-wrap">
						<img
							className="ballard-chart"
							src={chartSrc}
							alt="Ballard scoring chart"
						/>
					</div>

					
                    </div>
                  <div className="ballard-footer">
  <div className="ballard-signature">
    <div className="ballard-sign-line" />
    <div className="ballard-sign-label">PEDIATRICIAN</div>
  </div>
  
  <div className="ballard-default-footer">
    <div className="ballard-generated-line" />
    <div className="ballard-generated">Generated by: TCP T. TCP on 2026-04-22 03:16 pm</div>
  </div>
</div>
				</div>
			</div>
		</div>
	);
}
