import styles from "./BloodTransfusionSheet.module.css";

const formatGeneratedOn = (date = new Date()) => {
  const pad = (v) => String(v).padStart(2, "0");
  const h = date.getHours();
  const m = date.getMinutes();
  const ampm = h >= 12 ? "pm" : "am";
  const h12 = String(h % 12 || 12).padStart(2, "0");

  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(
    date.getDate()
  )} ${h12}:${pad(m)} ${ampm}`;
};

export default function BloodTransfusionSheet({
  patientName,
  patientData = {},
}) {
  const caseNum = patientData.caseNum || "";
  const hospitalNo = patientData.hospitalNo || "";
  const name = patientName || patientData.patientName || "";
  const ward = patientData.ward || "";
  const age = patientData.age || "";
  const sex = patientData.sex || "";
  const hrn = patientData.hrn || "";
  const generatedOn = patientData.generatedOn || formatGeneratedOn();

  return (
    <div className={styles.wrap}>
      <div className={styles.page}>
        
        {/* META HEADER */}
        <div className={styles.metaSection}>
          <div className={styles.metaCol}>
            <div className={styles.metaItem}>
              <span className={styles.label}>Case Number:</span>
              {caseNum ? (
                <span className={styles.value}>{caseNum}</span>
              ) : (
                <span className={`${styles.line} ${styles.lineMd}`} />
              )}
            </div>
            <div className={styles.metaItem}>
              <span className={styles.label}>Hospital No.:</span>
              <span>{hospitalNo}</span>
            </div>
            <div className={styles.metaItem}>
              <span className={styles.label}>Patient Name:</span>
              <span>{name}</span>
            </div>
          </div>

          <div className={styles.metaCol}>
            <div className={styles.metaItem}>
              <span className={styles.label}>Ward:</span>
              <span>{ward}</span>
            </div>
            <div className={styles.metaItem}>
              <span className={styles.label}>Age:</span>
              <span>{age}</span>
            </div>
            <div className={styles.metaItem}>
              <span className={styles.label}>Sex:</span>
              <span>{sex}</span>
            </div>
            <div className={styles.metaItem}>
              <span className={styles.label}>HRN:</span>
              {hrn ? (
                <span>{hrn}</span>
              ) : (
                <span className={`${styles.line} ${styles.lineMd}`} />
              )}
            </div>
          </div>
        </div>

        {/* TABLE */}
        <table className={styles.table}>
          <thead>
            <tr>
              <th className={styles.colBag}>BAG NO.</th>
              <th className={styles.colDate}>DATE & TIME STARTED</th>
              <th className={styles.colBlood}>BLOOD COMPONENT</th>
              <th className={styles.colType}>BLD TYPE</th>
              <th className={styles.colSerial}>SERIAL NO.</th>
              <th className={styles.colExpiry}>EXPIRATION DATE</th>
              <th className={styles.colDateTime}>DATE & TIME CONSUMED</th>
              <th className={styles.colNurse}>
                NURSE'S NAME AND SIGNATURE
              </th>
              <th className={styles.colRemarks}>REMARKS</th>
            </tr>
          </thead>

          <tbody>
            {Array.from({ length: 23 }).map((_, i) => (
              <tr key={i}>
                <td />
                <td />
                <td />
                <td />
                <td />
                <td />
                <td />
                <td />
                <td />
              </tr>
            ))}
          </tbody>
        </table>

        {/* FOOTER */}
        <div className={`${styles.footer} form-footer`}>
          Generated by: TCP T. TCP on {generatedOn}
        </div>
        
      </div>
    </div>
  );
}