import "./BloodTransfusionSheet.css";

export default function BloodTransfusionSheet() {
	return (
		<div className="bts-page">
			<div className="bts-meta-grid">
				<div className="bts-meta-col">
					<div className="bts-meta-item">
						<span className="bts-label">Case Number:</span>
						<span>ADM-2026-010617</span>
					</div>
					<div className="bts-meta-item">
						<span className="bts-label">Hospital No.:</span>
						<span>0000000020971</span>
					</div>
					<div className="bts-meta-item">
						<span className="bts-label">Patient Name:</span>
						<span>MATILOS , EUGENIA MAMBA</span>
					</div>
				</div>

				<div className="bts-meta-col">
					<div className="bts-meta-item">
						<span className="bts-label">Ward:</span>
						<span>ISOLATION - 6SAIS - BED 03</span>
					</div>
					<div className="bts-meta-item">
						<span className="bts-label">Age:</span>
						<span>67 year(s)</span>
					</div>
					<div className="bts-meta-item">
						<span className="bts-label">Sex:</span>
						<span>F</span>
					</div>
					<div className="bts-meta-item">
						<span className="bts-label">HRN:</span>
						<span className="bts-hrn-line" aria-label="HRN field" />
					</div>
				</div>
			</div>

			<table className="bts-table" aria-label="Blood transfusion tracking table">
				<thead>
					<tr>
						<th className="bts-col-bag">BAG NO.</th>
						<th className="bts-col-date">DATE & TIME STARTED</th>
						<th className="bts-col-blood">BLOOD COMPONENT</th>
						<th className="bts-col-type">BLD TYPE</th>
						<th className="bts-col-serial">SERIAL NO.</th>
						<th className="bts-col-expiry">EXPIRATION DATE</th>
						<th className="bts-col-date-time">DATE & TIME CONSUMED</th>
						<th className="bts-col-nurse">NURSE'S NAME AND SIGNATURE</th>
						<th className="bts-col-remarks">REMARKS</th>
					</tr>
				</thead>
				<tbody>
					{Array.from({ length: 18 }).map((_, index) => (
						<tr key={index}>
							<td className="bts-col-bag">&nbsp;</td>
							<td className="bts-col-date">&nbsp;</td>
							<td className="bts-col-blood">&nbsp;</td>
							<td className="bts-col-type">&nbsp;</td>
							<td className="bts-col-serial">&nbsp;</td>
							<td className="bts-col-expiry">&nbsp;</td>
							<td className="bts-col-date-time">&nbsp;</td>
							<td className="bts-col-nurse">&nbsp;</td>
							<td className="bts-col-remarks">&nbsp;</td>
						</tr>
					))}
				</tbody>
			</table>

			<div className="bts-footer form-footer">
				<div className="bts-footer-line" aria-hidden="true" />

				<div className="bts-default-footer">
					Generated by: TCP T. TCP on 2026-04-21 02:22 pm
				</div>
			</div>
		</div>
	);
}