import "./BloodCancellation.css";

const formatGeneratedOn = (date = new Date()) => {
	const pad = (value) => String(value).padStart(2, "0");
	const hours = date.getHours();
	const minutes = date.getMinutes();
	const ampm = hours >= 12 ? "pm" : "am";
	const hour12 = String(hours % 12 || 12).padStart(2, "0");

	return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${hour12}:${pad(minutes)} ${ampm}`;
};

export default function BloodCancellation({ patientName, patientData = {} }) {
	const caseNum = patientData.caseNum || patientData.caseNo || "";
	const name = patientName || patientData.patientName || patientData.fullName || "";
	const age = patientData.age || "";
	const sex = patientData.sex || "";
	const generatedOn = patientData.generatedOn || formatGeneratedOn();

	return (
		<div className="blood-cancel-page">
			<br />
			<br>
			</br>
			{/* Meta block */}
			<div className="blood-cancel-meta-block">
				<div className="blood-cancel-meta-row">
					<span className="blood-cancel-label">Case Number:</span>
					<span className="blood-cancel-value">{caseNum}</span>
				</div>
				<div className="blood-cancel-meta-row">
					<span className="blood-cancel-label">Name of Patient:</span>
					<span className="blood-cancel-value">{name}</span>
					<div className="blood-cancel-meta-inline">
						<span className="blood-cancel-label">Age:</span>
						<span className="blood-cancel-value">{age}</span>
						<span className="blood-cancel-label" style={{ marginLeft: "50px" }}>Sex:</span>
						<span className="blood-cancel-value">{sex}</span>
					</div>
				</div>
				<div className="blood-cancel-meta-row">
					<span className="blood-cancel-label">Blood Type:</span>
					<span className="blood-cancel-underline" />
				</div>
			</div>

			{/* Reasons */}
			<div className="blood-cancel-reasons-title">REASONS:</div>

			<div className="blood-cancel-reasons-body">
				{/* Left column — checkboxes */}
				<div className="blood-cancel-reasons-left">
					<div className="blood-cancel-checkbox-item">[ &nbsp;] Patient is febrile</div>
					<div className="blood-cancel-checkbox-item">[ &nbsp;] Patient died before transfusion</div>
					<div className="blood-cancel-checkbox-item">[ &nbsp;] Patient refusal/ No consent</div>
					<div className="blood-cancel-checkbox-item">[ &nbsp;] Medical problem before transfusion</div>
					<div className="blood-cancel-checkbox-item">[ &nbsp;] More then 30 minutes rule</div>
					<div className="blood-cancel-checkbox-item">[ &nbsp;] No intravenous access</div>
					<div className="blood-cancel-checkbox-item">[ &nbsp;] Patient for transfer/ Referred to other hospitals</div>
					<div className="blood-cancel-checkbox-item">[ &nbsp;] Other Reason</div>
				</div>

				{/* Right column — blood bag numbers */}
				<div className="blood-cancel-reasons-right">
					<div className="blood-cancel-blood-bag-item">
						<span>1. Blood Bag No.</span>
						<span className="blood-cancel-bag-line" />
					</div>
					<div className="blood-cancel-blood-bag-item">
						<span>2. Blood Bag No.</span>
						<span className="blood-cancel-bag-line" />
					</div>
					<div className="blood-cancel-blood-bag-item">
						<span>3. Blood Bag No.</span>
						<span className="blood-cancel-bag-line" />
					</div>
					<div className="blood-cancel-blood-bag-item">
						<span>4. Blood Bag No.</span>
						<span className="blood-cancel-bag-line" />
					</div>
					<div className="blood-cancel-blood-bag-item">
						<span>5. Blood Bag No.</span>
						<span className="blood-cancel-bag-line" />
					</div>
				</div>
			</div>

			{/* Prepared by */}
			<div className="blood-cancel-prepared">
				<div className="blood-cancel-prepared-line-wrap">
					<div className="blood-cancel-prepared-label">
						Prepared by:&nbsp;<span className="blood-cancel-prepared-sig-line" />
					</div>
					<div className="blood-cancel-prepared-sig-label">
						Signature over Printed Name of Nurse on Duty
					</div>
				</div>
			</div>

			{/* Footer */}
			<div className="blood-cancel-footer">
				Generated by: TCP T. TCP on {generatedOn}
			</div>

		</div>
	);
}