import './BTLConsent.css';

export default function BTLConsent() {
	return (
		<div className="btl-consent-page">
			<div className="btl-consent-main">
				<div className="btl-header-spacer" aria-hidden="true" />

				<div className="btl-form-meta">
					<div>FORM NO.:___________</div>
					<div>Revised.:___________</div>
				</div>

				<h2 className="btl-consent-title">BTL Consent Form</h2>

				<div className="btl-copy-block">
					<p>
						Ako si MATILOS , EUGENIA MAMBA, sakto sa edad nga maoy nagpapirma sa ubos, nagahangyo nga
						pagahimuon ug usa ka opersayon sa <span className="btl-inline-line" aria-hidden="true" />. Ako
						gihimo kining paghanyo sa kaugalingon nakong desisyon nga walay pagpugos ug walay angay nga
						pagkombinse nining mosunod:
					</p>

					<ol className="btl-consent-list">
						<li>Adunay mga temporaryong paaging pagkonrasepsyon nga mahimo para kanako ug sa akong kapares;</li>
						<li>Ang paagi nga himoon kanako maoy usa nga operasyon ug ang mga detalye gipasabot na kanako;</li>
						<li>Kining operasyon nga pagahimnon may pagka delikado ug naay kaakohan nga pareho gipasabot kanako;</li>
						<li>Kung magmalampuson ang maong operasyon dili nako manganak ug magka-anak pa;</li>
						<li>Ang resulta niining operasyon maoy permanente na;</li>
						<li>Mahimo nga bawion ang akong desisyon sa unsang orasa sa dili pa himoon ang operasyon.</li>
					</ol>
				</div>

				<div className="btl-signatures">
					<div className="btl-signature-row btl-signature-row-1">
						<div className="btl-signature-field">
							<div className="btl-signature-line" aria-hidden="true" />
							<div className="btl-signature-label">Firma sa Pasyente</div>
						</div>
						<div className="btl-signature-field">
							<div className="btl-signature-line" aria-hidden="true" />
							<div className="btl-signature-label">Firma sa Bana</div>
						</div>
						<div className="btl-signature-field">
							<div className="btl-signature-line" aria-hidden="true" />
							<div className="btl-signature-label">Petsa</div>
						</div>
					</div>

					<div className="btl-signature-row btl-signature-row-2">
						<div className="btl-signature-field btl-signature-wide">
							<div className="btl-signature-line" aria-hidden="true" />
							<div className="btl-signature-label">Firma sa Doktor o Delegadong Kauban</div>
						</div>
						<div className="btl-signature-field btl-signature-date">
							<div className="btl-signature-line" aria-hidden="true" />
							<div className="btl-signature-label">Petsa</div>
						</div>
					</div>

					<p className="btl-witness-note">
						Kung ang pasyente makabasa, usa nga iyang pinili nga pareho ang sinulithan ang kinahanglan mopirma sa
						maong deklarasyon.
					</p>

					<div className="btl-signature-row btl-signature-row-3">
						<div className="btl-signature-field btl-signature-left">
							<div className="btl-signature-line" aria-hidden="true" />
							<div className="btl-signature-label">Ngalan ug Pirma sa Testigo</div>
						</div>
						<div className="btl-signature-field btl-signature-right">
							<div className="btl-signature-line" aria-hidden="true" />
							<div className="btl-signature-label">Marka niang dakong Tudlo sa Tuo sa Pasyente</div>
						</div>
					</div>
				</div>
			</div>

			<div className="btl-consent-footer">Generated by: TCP T. TCP on 2026-04-21 01:02 pm</div>
		</div>
	);
}
