import PropTypes from "prop-types";
import { useEffect, useState } from "react";
import { formatGeneratedOn } from "../../utils/dateFormatter";
import { mapCardioFormData } from "../../utils/cardioMapper";
import "./CardioPulmonaryClearance.css";

export default function CardioPulmonaryClearance({ patientData }) {
  const [formData, setFormData] = useState(null);

  // ✅ SAFE DATA MAPPING
  useEffect(() => {
    console.log("RECEIVED patientData:", patientData);

    if (!patientData) {
      setFormData(null);
      return;
    }

    const mapped = mapCardioFormData(patientData);
    setFormData(mapped);
  }, [patientData]);

  const generatedBy = "TCP T. TCP";

  const generatedOn = formData?.generatedOn || formatGeneratedOn();

  // ✅ prevent blank screen flicker
  if (!patientData) {
    return <div>Loading patient data...</div>;
  }

  if (!formData) {
    return <div>Mapping patient data...</div>;
  }

  const {
    caseNumber,
    department,
    date,
    hospitalNo,
    patientName,
    sex,
    age,
  } = formData;

  return (
    <div className="cardio-clearance-page">
      <div className="cardio-clearance-main">

        <div className="cardio-header-spacer" />
        <br />

        {/* CASE NUMBER */}
        <div className="cardio-top-row">
          <span className="cardio-label">Case Number:</span>
          <span>{caseNumber}</span>
        </div>

        {/* DEPARTMENT + DATE */}
        <div className="cardio-top-row">
          <span className="cardio-label">Department:</span>
          <span>{department}</span>

          <span className="cardio-label cardio-date-label">Date:</span>
          <span>{date}</span>
        </div>

        {/* HOSPITAL NO */}
        <div className="cardio-top-row">
          <span className="cardio-label">Hospital No.:</span>
          <span>{hospitalNo}</span>
        </div>

        {/* PATIENT INFO */}
        <div className="cardio-top-row">
          <span className="cardio-label">Patient Name:</span>
          <span className="cardio-name-value">{patientName}</span>

          <span className="cardio-label">Sex:</span>
          <span>{sex}</span>

          <span className="cardio-label">Age:</span>
          <span>{age}</span>
        </div>

        <br />

        {/* FOOTER */}
        <div className="cardio-footer">
          Generated by: {generatedBy} on {generatedOn}
        </div>

      </div>
    </div>
  );
}

CardioPulmonaryClearance.propTypes = {
  patientData: PropTypes.any,
};