import { useMemo } from "react";
import "./CertificatePatientWardPreference.css";

export default function CertificatePatientWardPreference({ patientName, patientData }) {
  const name = patientName || "BAYSA , BABY BOY";

  const { dateStr, generatedOn } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const h = now.getHours();
    const m = now.getMinutes();
    const hh = String(h % 12 || 12).padStart(2, "0");
    const ampm = h < 12 ? "am" : "pm";

    const day = now.getDate();
    const suffix =
      day % 10 === 1 && day !== 11 ? "st"
      : day % 10 === 2 && day !== 12 ? "nd"
      : day % 10 === 3 && day !== 13 ? "rd"
      : "th";
    const monthName = now.toLocaleDateString("en-US", { month: "long" });
    const year = now.getFullYear();
    const dateStr = `${day}${suffix} of ${monthName} ${year}`;

    const generatedOn = `${year}-${pad(now.getMonth() + 1)}-${pad(day)} ${hh}:${pad(m)} ${ampm}`;
    return { dateStr, generatedOn };
  }, []);

  return (
    <div className="cpwp-page">


      <br></br>
      
      {/* ── THIS IS TO CERTIFY THAT ___ voluntarily agrees ── */}
      <div className="cpwp-certify-row">
        <span>THIS IS TO CERTIFY THAT</span>
        <span className="cpwp-inline-line" />
        <span>voluntarily agrees</span>
      </div>

      {/* ── (Name of requesting person) ── */}
      <div className="cpwp-req-label">(Name of requesting person)</div>

      {/* ── for my patient ___ to be admitted ── */}
      <div className="cpwp-patient-row">
        for my patient&nbsp;&nbsp;<strong>{name}</strong>&nbsp;&nbsp; to be admitted to any private room of this Hospital.
      </div>

      {/* ── NBB paragraph ── */}
      <p className="cpwp-nbb-para">
        <strong>If a No Balance Billing (NBB) recipient</strong>, I am fully aware that this admission is tantamount to the{" "}
        <strong>WAIVER</strong> of any benefits under such category.
      </p>

      {/* ── Furthermore paragraph ── */}
      <p className="cpwp-furthermore-para">
        <strong>Furthemore</strong>, I will abide to <strong>settling</strong> in <strong>full</strong> the hospital bill incurred upon discharge.
      </p>
      

      {/* ── WITNESS MY HAND ── */}
      <p className="cpwp-witness-hand">
        <strong>WITNESS MY HAND</strong> this {dateStr} at Agusan del Norte Provincial Hospital, Libertad,{" "}
        Butuan City.
      </p>

      {/* ── Signature block (centered) ── */}
      <div className="cpwp-sig-center">
        <div className="cpwp-sig-block">
          <div className="cpwp-sig-line" />
          <div className="cpwp-sig-label">Signature over printed name of Requesting Person</div>
        </div>
      </div>

      {/* ── WITNESS: label (centered) ── */}
      <div className="cpwp-witness-title">WITNESS:</div>
      <br />

      {/* ── Witness signature (centered container, left text) ── */}
      <div className="cpwp-witness-sig-center">
        <div className="cpwp-sig-block-witness">
          <div className="cpwp-sig-line" />
          <div className="cpwp-sig-label">Signature over printed name of Admitting Cler/ER Staff</div>
        </div>
      </div>

      {/* ── Footer ── */}
      <div className="cpwp-footer">
        Generated by: TCP T. TCP on {generatedOn}
      </div>

    </div>
  );
}