import { useMemo } from "react";
import "./CertificateOfNoVacancy.css";

export default function CertificateOfNoVacancy({ patientName, patientData }) {
	const name  = patientName          || "BAYSA , BABY BOY";
	const ward  = patientData?.ward    || "OB GYNE - OB 2 - BED 03 - NB";

	const { dayStr, monthYear, generatedOn } = useMemo(() => {
		const now = new Date();
		const pad = (n) => String(n).padStart(2, "0");
		const h = now.getHours();
		const m = now.getMinutes();
		const ampm = h >= 12 ? "am" : "am";
		const hh = String(h % 12 || 12).padStart(2, "0");
		const timeStr = `${hh}:${pad(m)} ${ampm}`;

		const day = now.getDate();
		const monthName = now.toLocaleDateString("en-US", { month: "long" });
		const year = now.getFullYear();
		const mo = pad(now.getMonth() + 1);
		const d = pad(day);

		// "22nd of April 2026"
		const ordinal = (n) => {
			const s = ["th","st","nd","rd"];
			const v = n % 100;
			return n + (s[(v-20)%10] || s[v] || s[0]);
		};

		const dayStr   = ordinal(day);
		const monthYear = `${monthName} ${year}`;

		// "April 22,2026" format used in the body
		const bodyDate = `${monthName} ${day},${year}`;

		const generatedOn = `${year}-${mo}-${d} ${timeStr}`;
		return { dayStr, monthYear, bodyDate, generatedOn };
	}, []);

	// Build the body date string inline
	const now = new Date();
	const monthName = now.toLocaleDateString("en-US", { month: "long" });
	const day = now.getDate();
	const year = now.getFullYear();
	const bodyDate = `${monthName} ${day},${year}`;

	// Ordinal helper
	const ordinal = (n) => {
		const s = ["th","st","nd","rd"];
		const v = n % 100;
		return n + (s[(v-20)%10] || s[v] || s[0]);
	};

	return (
		<div className="cnv-page">

			<br>
			</br>

			{/* ── Paragraph 1 ── */}
			<p className="cnv-para cnv-center">
				THIS IS TO CERTIFY THAT {name} is admitted to the
			</p>

			{/* ── Paragraph 2 ── */}
			<p className="cnv-para cnv-center">
				{ward} at the private room of this hospital due to lack of vacancy in the wards, as of {bodyDate} .
			</p>

			{/* ── Paragraph 3 — NBB ── */}
			<p className="cnv-para cnv-justify cnv-indent">
				<strong>If a No Balance Billing (NBB) recipient</strong>, I am fully aware that such benefits are not waived in any way.
			</p>

			{/* ── Paragraph 4 — WITNESS MY HAND ── */}
			<p className="cnv-para cnv-justify cnv-indent">
				<strong>WITNESS MY HAND this</strong> {ordinal(day)} of {monthName} {year} at Agusan del Norte Provincial Hospital, Libertad, Butuan City.
			</p>

			{/* ── Signature: Requesting Person ── */}
            <br />
			<div className="cnv-sig-wrap">
				<div className="cnv-sig-block">
					<div className="cnv-sig-line" />
					<p className="cnv-sig-label">Signature over printed name of Requesting Person</p>
				</div>
			</div>
            <br />

			{/* ── WITNESS label ── */}
			<p className="cnv-witness-label">WITNESS:</p>
            <br />

			{/* ── Signature: Admitting Clerk ── */}
			  <div className="cnv-sig-wrap">
                <div className="cnv-sig-block">
                    <div className="cnv-sig-line" />
                    <p className="cnv-sig-label">Signature over printed name of Admitting Cler/ER Staff</p>
                </div>
                </div>

			{/* ── Footer ── */}
			<div className="cnv-footer">
				Generated by: TCP T. TCP on {generatedOn}
			</div>

		</div>
	);
}