import { useMemo } from "react";
import "./ChestTubeThoracostomy.css";

export default function ChestTubeThoracostomy({ patientName, patientData }) {
  const name   = patientName             || "FELISELDA , CIAN REIN BAYSA";
  const hospNo = patientData?.hospitalNo || "000000000021041";
  const sex    = patientData?.sex        || "M";
  const age    = patientData?.age        || "1 hour(s)";
  const caseNo = patientData?.caseNo     || "ADM-2026-010651";

  const { generatedOn } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const h = now.getHours();
    const m = now.getMinutes();
    const ampm = h >= 12 ? "pm" : "am";
    const hh = String(h % 12 || 12).padStart(2, "0");
    const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(m)} ${ampm}`;
    return { generatedOn };
  }, []);

  const columns = ["Date & Time", "Received", "End of Shift", "Output", "Signature"];

  return (
    <div className="ctt-page">

      {/* ── Main Table ── */}
      <table className="ctt-table">
        <thead>
          <tr>
            {columns.map((col, i) => (
              <th key={i}>{col}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {Array.from({ length: 25 }).map((_, i) => (
            <tr key={i}>
              {columns.map((_, j) => (
                <td key={j} />
              ))}
            </tr>
          ))}
        </tbody>
      </table>

      {/* ── Patient Info ── */}
      <div className="ctt-info-block">
        <div className="ctt-info-row">
          <span className="ctt-info-label">Hospital No.:</span>
          <span>{hospNo}</span>
        </div>
        <div className="ctt-info-row">
          <span className="ctt-info-label">Patient Name:</span>
          <span>{name}</span>
        </div>
        <div className="ctt-info-row">
          <span className="ctt-info-label">Sex:</span>
          <span>{sex}</span>
        </div>
        <div className="ctt-info-row">
          <span className="ctt-info-label">Age:</span>
          <span>{age}</span>
        </div>
        <div className="ctt-info-row">
          <span className="ctt-info-label">Case Number:</span>
          <span>{caseNo}</span>
        </div>
      </div>

      {/* ── Footer ── */}
      <div className="ctt-footer form-footer">
        Generated by: TCP T. TCP on {generatedOn}
      </div>

    </div>
  );
}