import { useMemo } from 'react';
import './ChildImmunizationRecord.css';

const chartPlaceholderSrc = 'src/modules/forms/img/child immunization record.jpg';
const imagePlaceholderSrc = 'src/modules/forms/img/child immunization record2.jpg';


const ChildImmunizationRecord = ({ patientName, patientData }) => {
  const caseNumber = patientData?.caseNumber || "ADM-2026-010651";
  const patientNameVal = patientName || "FELISELDA , CIAN REIN BAYSA";
  const hospitalNo = patientData?.hospitalNo || "000000000021041";
  const sex = patientData?.sex || "M";
  const age = patientData?.age || "1 hour(s)";

  const { generatedOn } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const h = now.getHours();
    const m = now.getMinutes();
    const ampm = h >= 12 ? "pm" : "am";
    const hh = String(h % 12 || 12).padStart(2, "0");
    const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(m)} ${ampm}`;
    return { generatedOn };
  }, []);

  return (
    <div className="neuro-vital-signs-container">
      <div className="neuro-vital-signs">
        <section className="chart-section" aria-label="Child immunization record chart image">
          <img
            className="chart-image"
            src={chartPlaceholderSrc}
            alt="Child immunization record chart placeholder"
          />
              </section>
              <section className="chart-section" aria-label="Child immunization record chart image">
          <img
            className="chart-image"
            src={imagePlaceholderSrc}
            alt="Child immunization record chart placeholder"
          />
        </section>

        <div className="form-footer"> Generated by: TCP T. TCP on {generatedOn}</div>
      </div>
    </div>
  );
};

export default ChildImmunizationRecord;