import { useMemo } from 'react';
import styles from './ChildImmunizationRecord.module.css';

const chartPlaceholderSrc = 'src/modules/forms/img/child immunization record.jpg';
const imagePlaceholderSrc = 'src/modules/forms/img/child immunization record2.jpg';


const ChildImmunizationRecord = ({ patientName, patientData }) => {
  const caseNumber = patientData?.caseNumber || "";
    const patientNameVal = patientName || "";
    const hospitalNo = patientData?.hospitalNo || "";
  const sex = patientData?.sex || "";
  const age = patientData?.age || "";

  const { generatedOn } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const h = now.getHours();
    const m = now.getMinutes();
    const ampm = h >= 12 ? "pm" : "am";
    const hh = String(h % 12 || 12).padStart(2, "0");
    const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(m)} ${ampm}`;
    return { generatedOn };
  }, []);

  return (
    <div className={styles.container}>
      <div className={styles.record}>
        <section className={styles.chartSection} aria-label="Child immunization record chart image">
          <img
            className={styles.chartImage}
            src={chartPlaceholderSrc}
            alt="Child immunization record chart placeholder"
          />
              </section>
              <section className={styles.chartSection} aria-label="Child immunization record chart image">
          <img
            className={styles.chartImage}
            src={imagePlaceholderSrc}
            alt="Child immunization record chart placeholder"
          />
        </section>

        <div className={`${styles.footer} form-footer`}> Generated by: TCP T. TCP on {generatedOn}</div>
      </div>
    </div>
  );
};

export default ChildImmunizationRecord;
