import { useState } from 'react';
import './ChildImmunizationRecord.css';

const chartPlaceholderSrc = 'src/modules/forms/img/child immunization record.jpg';
const imagePlaceholderSrc = 'src/modules/forms/img/child immunization record2.jpg';


const ChildImmunizationRecord = () => {
  const [formData, setFormData] = useState({
    caseNumber: 'ADM-2026-010651',
    patientName: 'FELISELDA , CIAN REIN BAYSA',
    hospitalNo: '000000000021041',
    sex: 'M',
    age: '1 hour(s)',
    ht: '',
    wt: '',
    t: '',
    rr: '',
    pr: '',
    bp: '',
    date: 'April 22, 2026',
    preOpDx: '',
    asa: '',
    operationProposed: '',
    preNeeds: '',
  });

  const handleChange = (field, value) => {
    setFormData(prev => ({
      ...prev,
      [field]: value,
    }));
  };

  return (
    <div className="neuro-vital-signs-container">
      <div className="neuro-vital-signs">
        <div className="header-reserved-space" aria-hidden="true" />

    

        <section className="chart-section" aria-label="Child immunization record chart image">
          <img
            className="chart-image"
            src={chartPlaceholderSrc}
            alt="Child immunization record chart placeholder"
          />
              </section>
              

              <section className="chart-section" aria-label="Child immunization record chart image">
          <img
            className="chart-image"
            src={imagePlaceholderSrc}
            alt="Child immunization record chart placeholder"
          />
        </section>

        <div className="form-footer"> Generated by: TCP T. TCP on April 22, 2026</div>
      </div>
    </div>
  );
};

export default ChildImmunizationRecord;