import { useMemo } from "react";
import "./ClaimOfCadaver.css";

export default function ClaimOfCadaver({ patientName, patientData }) {
  const name = patientName || "BAYSA , BABY BOY";

  const { dateStr, timeStr, generatedOn } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");

    const dateStr = now.toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    const h = now.getHours();
    const m = now.getMinutes();
    const hh = String(h % 12 || 12).padStart(2, "0");
    const ampm = h < 12 ? "AM" : "PM";
    const timeStr = `${hh}:${pad(m)} ${ampm}`;

    const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${String(h % 12 || 12).padStart(2, "0")}:${pad(m)} ${ampm.toLowerCase()}`;

    return { dateStr, timeStr, generatedOn };
  }, []);

  return (
    <div className="coc-page">

      {/* ── Date / Time ── */}
      <div className="coc-top-row">
        <span>Date: {dateStr}</span>
        <span>Time: {timeStr}</span>
      </div>

      {/* ── Statement ── */}
      <br />
      <div className="coc-statement">
        After being pronounced dead by a physician, I am claiming the cadaver of {name}
      </div>

      {/* ── Two signature blocks ── */}
      <br />
      <br />
      <div className="coc-sig-row">
        <div className="coc-sig-block">
          <div className="coc-sig-line" />
          <div className="coc-sig-label">Signature Over Printed Name of Claimant</div>
        </div>
        <div className="coc-sig-block">
          <div className="coc-sig-line" />
          <div className="coc-sig-label">Signature Over Printed Name of Witness</div>
        </div>
      </div>

      {/* ── Relationship block ── */}
      <br />
      <div className="coc-relationship-block">
        <div className="coc-sig-line" />
        <div className="coc-sig-label">Relationship to the Deceased</div>
      </div>

      {/* ── NB note ── */}
      <br />
      <div className="coc-nb">
        NB: Explained in a dialect known to the claimant by nurse on duty
      </div>

      {/* ── Footer ── */}
      <div className="coc-footer form-footer">
        Generated by: TCP T. TCP on {generatedOn}
      </div>

    </div>
  );
}