import { useMemo } from "react";
import "./CommitmentToBreastfeeding.css";

export default function CommitmentToBreastfeeding({ patientName, patientData }) {
  const name = patientName || "BAYSA , BABY BOY";

  const { dateStr, generatedOn } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const h = now.getHours();
    const m = now.getMinutes();
    const hh = String(h % 12 || 12).padStart(2, "0");
    const ampm = h < 12 ? "am" : "pm";
    const dateStr = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`;
    const generatedOn = `${dateStr} ${hh}:${pad(m)} ${ampm}`;
    return { dateStr, generatedOn };
  }, []);

  return (
    <div className="ctb-page">
      <br />
      <div className="ctb-date-row">
        <strong>Date:</strong> {dateStr}
      </div>

      {/* ── TO WHOM IT MAY CONCERN ── */}
      <div className="ctb-to-whom">TO WHOM IT MAY CONCERN:</div>

      {/* ── Body ── */}
      <div className="ctb-body">
        This is to signify that I, {name} of P10, DOÑA TELESFORA, TUBAY, AGUSAN DEL NORTE
        <br />
        after having been fully informed and motivated on the benefits derived from breastfeeding by the staff of this hospital, promised
        to breastfeed my child right after delivery and will exclusively do so and sustain much even after my discharge from this hospital
        until 4-6 months thereafter.
      </div>

      <br />
      <div className="ctb-sig-pair">
        <div className="ctb-sig-block">
          <div className="ctb-sig-line" />
          <div className="ctb-sig-label">Husband's Signature</div>
        </div>
        <div className="ctb-sig-block">
          <div className="ctb-sig-line" />
          <div className="ctb-sig-label">Patient's Signature</div>
        </div>
      </div>

      <br /><br />
      <div className="ctb-witness-center">
        <div className="ctb-witness-block">
          <div className="ctb-sig-line" />
          <div className="ctb-sig-label">Witness</div>
        </div>
      </div>

      {/* ── Footer ── */}
      <div className="ctb-footer">
        Generated by: TCP T. TCP on {generatedOn}
      </div>

    </div>
  );
}