import { useMemo } from "react";
import "./ConsentToCare.css";

export default function ConsentToCare({ patientName, patientData }) {
	const name       = patientName            || "BAYSA , BABY BOY";
	const sex        = patientData?.sex       || "M";
	const age        = patientData?.age       || "1 hour(s)";
	const caseNum    = patientData?.caseNum   || "ADM-2026-010651";
	const hospitalNo = patientData?.hospitalNo || "000000000021041";

	const { dateStr, generatedOn } = useMemo(() => {
		const now = new Date();
		const pad = (n) => String(n).padStart(2, "0");
		const h = now.getHours();
		const m = now.getMinutes();
		const ampm = h >= 12 ? "am" : "am";
		const hh = String(h % 12 || 12).padStart(2, "0");
		const timeStr = `${hh}:${pad(m)} ${ampm}`;
		const y = now.getFullYear();
		const mo = pad(now.getMonth() + 1);
		const d = pad(now.getDate());
		const dateStr = `${mo}-${d}-${y}`;
		const generatedOn = `${y}-${mo}-${d} ${timeStr}`;
		return { dateStr, generatedOn };
	}, []);

	return (
		<div className="ctc-page">
			<br />
			<table className="ctc-info-table">
				<tbody>
					<tr>
						<td className="ctc-info-label">Case No.</td>
						<td className="ctc-info-colon">:</td>
						<td className="ctc-info-value">{caseNum}</td>
					</tr>
					<tr>
						<td className="ctc-info-label">Hospital No.</td>
						<td className="ctc-info-colon">:</td>
						<td className="ctc-info-value">{hospitalNo}</td>
					</tr>
					<tr>
						<td className="ctc-info-label">Patient's Name</td>
						<td className="ctc-info-colon">:</td>
						<td className="ctc-info-value">{name}</td>
					</tr>
					<tr>
						<td className="ctc-info-label">Sex</td>
						<td className="ctc-info-colon">:</td>
						<td className="ctc-info-value">{sex}</td>
					</tr>
					<tr>
						<td className="ctc-info-label">Age</td>
						<td className="ctc-info-colon">:</td>
						<td className="ctc-info-value">{age}</td>
					</tr>
				</tbody>
			</table>

			{/* ── Paragraph 1 ── */}
			<p className="ctc-para">
				1. I HEREBY AUTHORIZED Dr.
				<span className="ctc-inline-line" style={{ width: "300px" }} />
				 and the staff of this hospital to perform treatment and procedures deemed necessary for my care.
			</p>

			{/* ── Paragraph 2 ── */}
			<p className="ctc-para">
				2. I ALSO GIVE AUTHORIZATION for the hospital to supply information for my medical records, my insurance and for my attorney.
			</p>

			{/* ── Signature row 1: Witness | Patient ── */}
			<div className="ctc-sig-row">
				<div className="ctc-sig-block">
					<div className="ctc-sig-line" />
					<p className="ctc-sig-label">Signature of Witness</p>
				</div>
				<div className="ctc-sig-block">
					<div className="ctc-sig-line" />
					<p className="ctc-sig-label">Signature of Patient</p>
				</div>
			</div>

			{/* ── Paragraph 3 ── */}
			<div className="ctc-para3">
				<p className="ctc-para3-text">
					3. I,&nbsp;
					<span className="ctc-inline-line" style={{ width: "300px" }} />
					&nbsp;being the next of kin of
					<span className="ctc-inline-line" style={{ width: "300px" }} />
					&nbsp;and the staff of this hospital to perform necessary treatment.
				</p>
				<p className="ctc-para3-body">
					The authorization must be signed by the patient or the next kin in case of minor or if the patient is physically and mentally incompetent. Patient is a minor of
					<span className="ctc-inline-line" style={{ width: "300px" }} />
					&nbsp;. Patient is unable to sign because of
					<span className="ctc-inline-line" style={{ width: "250px" }} />
                    hereby authorized Dr.&nbsp;
					<span className="ctc-inline-line" style={{ width: "200px" }} />
				</p>
			</div>

			{/* ── Signature row 2: Witness | Next Kin + Date | Relation ── */}
            <br />
            <br />
			<div className="ctc-sig-row ctc-sig-row-bottom">
				<div className="ctc-sig-block">
					<div className="ctc-sig-line" />
					<p className="ctc-sig-label">Signature of Witness</p>
					<p className="ctc-sig-date">{dateStr}</p>
				</div>
                <br />
				<div className="ctc-sig-block">
					<div className="ctc-sig-line" />
					<p className="ctc-sig-label">Signature of Next Kin</p>
                    <br />
                    <br />
					<div className="ctc-sig-line ctc-sig-line-relation" />
					<p className="ctc-sig-label">Relation to Patient</p>
				</div>
			</div>

			{/* ── Footer ── */}
			<div className="ctc-footer">
				Generated by: TCP T. TCP on {generatedOn}
			</div>

		</div>
	);
}