import { useMemo } from "react";
import "./ConsentToSurgery.css";

export default function ConsentToSurgery({ patientName, patientData }) {
  const name = patientName || "BAYSA , BABY BOY";

  const { dateStr, generatedOn } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const h = now.getHours();
    const m = now.getMinutes();
    const hh = String(h % 12 || 12).padStart(2, "0");
    const ampm = h < 12 ? "am" : "pm";

    const dateStr = now.toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(m)} ${ampm}`;
    return { dateStr, generatedOn };
  }, []);

  return (
    <div className="csa-page">

      {/* ── Paragraph 1 ── */}
      <div className="csa-para">
        <span className="csa-para-num">1.</span>
        <span className="csa-para-body">
          I HEREBY authorize Dr. <span className="csa-blank" />, Dr. <span className="csa-blank" /> and staff of Agusan del Norte
          Provincial Hospital to perform <span className="csa-blank-lg" /> under{" "}
          <span className="csa-blank-lg" /> and such additional operation and procedure/s which is/are
          considered necessary on the basis of there being a truth to the life found during the course of the said operation.
        </span>
      </div>

      {/* ── Paragraph 2 ── */}
      <div className="csa-para">
        <span className="csa-para-num">2.</span>
        <span className="csa-para-body">
          The nature and purpose of the operation, the risks involved, and the possibility and implications have been
          explained to me in my dialect or in language which I understand. I acknowledge that no guarantee has been
          made as to the results that be obtained.
        </span>
      </div>

      {/* ── First signature pair: Witness (left) | Patient name + sig (right) ── */}
      <div className="csa-sig-pair">
        <div className="csa-sig-left">
          <div className="csa-sig-line" />
          <div className="csa-sig-label">Signature over Printed Name of Witness</div>
          <div className="csa-sig-date">{dateStr}</div>
          <div className="csa-sig-date-label">Date</div>
        </div>
        <div className="csa-sig-right">
          <div className="csa-sig-name">{name}</div>
          <div className="csa-sig-line" />
          <div className="csa-sig-label">Signature over Printed Name of Patient</div>
          <div className="csa-sig-date">{dateStr}</div>
          <div className="csa-sig-date-label">Date</div>
        </div>
      </div>

      {/* ── Authorization note ── */}
      <div className="csa-auth-note">
        This authorization must be signed by the patient or next of kin in the case of the minor or where the patient is physically
        or mentally incompetent.<br /> <br />
        Patient is unable to sign because <span className="csa-blank-unable" />.
      </div>

      {/* ── I, ___ hereby authorized row ── */}
      <div className="csa-hereby-row">
        I,<span className="csa-blank-hereby-name" />hereby authorized Dr. <span className="csa-blank-hereby-dr" />, Dr. <span className="csa-blank-hereby-dr2" /> and
      </div>
      <div className="csa-hereby-indent">
        the staff of the said hospital to perform the surgery.
      </div>

      {/* ── Second signature pair ── */}
      <br />
      <div className="csa-sig-pair2">
        <div className="csa-sig2-left">
          <div className="csa-sig2-line" />
          <div className="csa-sig2-label">Signature over Printed Name of Witness</div>
        </div>
        <div className="csa-sig2-right">
          <div className="csa-sig2-line" />
          <div className="csa-sig2-label">Signature over Printed Name of Next of Kin</div>
          <br />
          <br />
          <div className="csa-relationship-block" style={{ marginTop: "4mm" }}>
            <div className="csa-sig2-line" />
            <div className="csa-sig2-label">Relationship to the Patient</div>
          </div>
        </div>
      </div>

      {/* ── Date pair for second sigs ── */}
      <div className="csa-date-pair">
        <div className="csa-date-block">
          <div className="csa-date-val">{dateStr}</div>
          <div className="csa-date-label">Date</div>
        </div>
        <div className="csa-date-block">
          <div className="csa-date-val">{dateStr}</div>
          <div className="csa-date-label">Date</div>
        </div>
      </div>

      {/* ── Footer ── */}
      <div className="csa-footer">
        Generated by: TCP T. TCP on {generatedOn}
      </div>

    </div>
  );
}