import { useMemo } from "react";
import "./DAMAForm.css";

const SigBlock = ({ label, dateStr }) => (
  <div className="dama-sig-block">
    <div className="dama-sig-line" />
    <div className="dama-sig-label">{label}</div>
    <div className="dama-date-value">{dateStr}</div>
    <div className="dama-date-label">Date</div>
  </div>
);

export default function DAMAForm({ patientName, patientData }) {
  const name = patientName || "";

  const { dateStr, generatedOn } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const h = now.getHours();
    const m = now.getMinutes();
    const ampm = h >= 12 ? "pm" : "am";
    const hh = String(h % 12 || 12).padStart(2, "0");
    const dateStr = now.toLocaleDateString("en-US", {
      year: "numeric", month: "long", day: "numeric",
    });
    const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(m)} ${ampm}`;
    return { dateStr, generatedOn };
  }, []);

  const UL = ({ width = "150px" }) => (
    <span className="dama-ul" style={{ width }} />
  );

  return (
    <div className="dama-page">
      <br />
      <p className="dama-opening">
        I <UL width="160px" /> hereby certify that I am leaving/that I am causing the discharge of{" "}
        {name} going home againts medical advice. I have been informed of the danger involved and I release
        the hospital and its staff from all liabilites for any ill effects which ma result from this action.
      </p>

      {/* ── Signature row 1 ── */}
      <div className="dama-sig-row">
        <SigBlock label="Signature of Witness"         dateStr={dateStr} />
        <SigBlock label="Signature of Patient/Relative" dateStr={dateStr} />
      </div>

      {/* ── Body paragraph ── */}
      <p className="dama-body">
        The patient {name} left the hospital not withstanding medical advice that he/she was not ready for discharge
        and that leaving the hospital at this time was dangerous and might result in serious complications. The patient refused to sign
        the above consent
      </p>

      {/* ── Signature row 2 ── */}
      <div className="dama-sig-row">
        <SigBlock label="Signature of Witness"         dateStr={dateStr} />
        <SigBlock label="Signature of Patient/Relative" dateStr={dateStr} />
      </div>

      {/* ── Footer ── */}
      <div className="dama-footer">
        Generated by: TCP T. TCP on {generatedOn}
      </div>

    </div>
  );
}