import { useMemo } from "react";
import "./DoctorsOrder.css";

export default function DoctorsOrder({ patientName, patientData }) {
	const name       = patientName             || "PELISCO , BABY GIRL";
	const sex        = patientData?.sex        || "F";
	const age        = patientData?.age        || "0";
	const caseNum    = patientData?.caseNum    || "ADM-2026-010623";
	const hospitalNo = patientData?.hospitalNo || "000000000020997";

	const { generatedOn } = useMemo(() => {
		const now = new Date();
		const pad = (n) => String(n).padStart(2, "0");
		const h = now.getHours();
		const m = now.getMinutes();
		const ampm = h >= 12 ? "pm" : "am";
		const hh = String(h % 12 || 12).padStart(2, "0");
		const timeStr = `${hh}:${pad(m)} ${ampm}`;
		const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${timeStr}`;
		return { generatedOn };
	}, []);

	const ROW_COUNT = 25;

	return (
		<div className="do-page">
			<br />
			<table className="do-table">
				<thead>
					<tr>
						<th className="do-th do-col-datetime">DATE/TIME</th>
						<th className="do-th do-col-progress">PROGRESS NOTES</th>
						<th className="do-th do-col-order">DOCTOR'S ORDER</th>
					</tr>
				</thead>
				<tbody>
					{Array.from({ length: ROW_COUNT }).map((_, i) => (
						<tr key={i} className="do-tr">
							<td className="do-td do-col-datetime" />
							<td className="do-td do-col-progress" />
							<td className="do-td do-col-order" />
						</tr>
					))}
				</tbody>
			</table>

			{/* ── Patient Info Block ── */}
			<div className="do-patient-info">
				<p>
					<span className="do-info-label">Hospital No.:</span> {hospitalNo}&nbsp;&nbsp;&nbsp;
					<span className="do-info-label">Case Number:</span> {caseNum}
				</p>
				<p>
					<span className="do-info-label">Patient Name:</span> {name}&nbsp;&nbsp;&nbsp;
					<span className="do-info-label">Sex:</span> {sex}&nbsp;&nbsp;&nbsp;
					<span className="do-info-label">Age:</span> {age}
				</p>
			</div>

			{/* ── Footer ── */}
			<div className="do-footer">
				Generated by: TCP T. TCP on {generatedOn}
			</div>

		</div>
	);
}