import { useMemo } from "react";
import "./FamilyPlanning.css";

export default function FamilyPlanning({ patientName, patientData }) {
	const name      = patientName           || "BAYSA , BABY BOY";
	const address   = patientData?.address  || "P10, DOÑA TELESFORA, TUBAY, AGUSAN DEL NORTE";
	const birthdate = patientData?.birthdate|| "April 22, 2026";
	const age       = patientData?.age      || "1 hour(s)";
	const gp        = patientData?.gp       || "";

	const { dateStr, generatedOn } = useMemo(() => {
		const now = new Date();
		const pad = (n) => String(n).padStart(2, "0");
		const h = now.getHours();
		const m = now.getMinutes();
		const ampm = h >= 12 ? "am" : "am";
		const hh = String(h % 12 || 12).padStart(2, "0");
		const dateStr = now.toLocaleDateString("en-US", {
			year: "numeric", month: "long", day: "numeric",
		});
		const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(m)} ${ampm}`;
		return { dateStr, generatedOn };
	}, []);

	const referOptions = [
		{ label: "FP/ ARH CLINIC", highlight: true },
		{ label: "OB/GYNE",        highlight: false },
		{ label: "OR/DR",          highlight: false },
		{ label: "OPD",            highlight: false },
		{ label: "Pedia",          highlight: false },
		{ label: "OTHERS",         highlight: false },
	];

	return (
		<div className="fp-page">

			{/* ── DATE ── */}
			<div className="fp-date-line">DATE: {dateStr}</div>

			{/* ── Instruction ── */}
			<div className="fp-instruction">Please check the appropriate box:</div>

			{/* ── REFER FROM / REFER TO ── */}
			<table className="fp-refer-table">
				<tbody>
					<tr>
						<td className="fp-label-cell">REFER FROM:</td>
						{referOptions.map((opt, i) => (
							<td key={i} className={opt.highlight ? "fp-highlight" : ""}>
								[ ] {opt.label}
							</td>
						))}
					</tr>
					<tr>
						<td className="fp-label-cell">REFER TO:</td>
						{referOptions.map((opt, i) => (
							<td key={i} className={opt.highlight ? "fp-highlight" : ""}>
								[ ] {opt.label}
							</td>
						))}
					</tr>
				</tbody>
			</table>

			{/* ── Patient Info ── */}
			<table className="fp-info-table">
				<tbody>
					<tr>
						<td colSpan={3}>
							<span className="fp-field-label">Name of Patient:</span> {name}
						</td>
					</tr>
					<tr>
						<td colSpan={3}>
							<span className="fp-field-label">Address:</span> {address}
						</td>
					</tr>
					<tr>
						<td style={{ width: "40%" }}>
							<span className="fp-field-label">Birthdate:</span> {birthdate}
						</td>
						<td style={{ width: "30%" }}>
							<span className="fp-field-label">Age:</span> {age}
						</td>
						<td style={{ width: "30%" }}>
							<span className="fp-field-label">G/P:</span> {gp}
						</td>
					</tr>
				</tbody>
			</table>

			{/* ── Reason for Referral ── */}
			<div className="fp-reason-title">Reason for Referral:</div>
			<div className="fp-reason-grid">
				<div className="fp-checkbox-item"><span>[  ]</span><span>Family Planning Counseling and ARH Services</span></div>
				<div className="fp-checkbox-item"><span>[  ]</span><span>Delivery</span></div>
				<div className="fp-checkbox-item"><span>[  ]</span><span>Prenatal Check-up</span></div>
				<div className="fp-checkbox-item"><span>[  ]</span><span>Postnatal Check-up</span></div>
				<div className="fp-checkbox-item"><span>[  ]</span><span>General Check-up</span></div>
				<div className="fp-checkbox-item"><span>[  ]</span><span>Others:________</span></div>
			</div>

			{/* ── Referred By ── */}
			<div className="fp-referred-by">Referred By:</div>

			{/* ── Signature lines ── */}
			<div className="fp-sig-row">
				<span className="fp-sig-label">Name and Signature:</span>
				<div className="fp-sig-line" />
			</div>
			<div className="fp-sig-row">
				<span className="fp-sig-label">Position/Designation:</span>
				<div className="fp-sig-line" />
			</div>

			{/* ── Footer ── */}
			<div className="fp-footer form-footer">
				Generated by: TCP T. TCP on {generatedOn}
			</div>

		</div>
	);
}