export const FORM_CATALOG = [
  "ABTC Form",
  "ABTC Treatment Record",
  "Advance Directive Do Not Resuscitate (DNR) / Do not Intubate Form",
  "Aldrete Score (Post Anesthesia Recovery Score) Form",
  "Anesthesia Record",
  "APGAR Score Form",
  "Ballard Score",
  "Blood Cancellation Form",
  "Blood Request Form (Adult)",
  "Blood Request Form (Pedia)",
  "Blood Transfusion Reaction Registry",
  "Blood Transfusion Sheet",
  "BTL Consent Form",
  "Cardio-Pulmonary Clearance Form",
  "Certificate of No Vacancy",
  "Certificate of Patient Ward Preference",
  "Certificate of Ward Preference",
  "Certification of Isolation Recommendation",
  "Chest Tube Thoracostomy Sheet",
  "Child Immunization Record",
  "Claim of Cadaver",
  "Clinical Cover Sheet",
  "Clinical Referral Slip",
  "Commitment to Breastfeeding",
  "Consent to Care",
  "Consent to Surgery and Anesthesia Form",
  "Daily Weight and Abdominal Girth",
  "Discharge Against Medical Advice (DAMA) / Out on Pass Form",
  "Discharge Plan/Referral Slip",
  "Doctor's Order (for pedia)",
  "Doctor's Order Form",
  "ECG TRACING",
  "Family Planning",
  "Histopathology/Cytology Request Form",
  "Intake and Output Sheet",
  "IVF Sheet",
  "Kardex Sheet",
  "Laboratory Request Form (outside)",
  "Laboratory Results",
  "Lubchenco",
  "Medical Abstract / Discharge Summary Form",
  "Medication Sheet",
  "MIS Safety Checklist",
  "Monitoring Sheet",
  "Neuro Vital Signs Stats Glasgow Coma Scale Less Than 2 years old",
  "Neuro Vital Signs Stats Glasgow Coma Scale More Than 2 years old",
  "Neurologic Examination Form",
  "Newborn Personal Information Sheet",
  "Newborn Physical Examination Sheet",
  "Newborn Tag",
  "Nurse's Notes Form",
  "Other Laboratory Request",
  "Otoacoustic Emission Results",
  "Oxygen Consumption Sheet",
  "Pagtugot (Waiver)",
  "Partograph",
  "Phototherapy Form",
  "Post Anesthesia Care Unit Nurse's Notes Form",
  "Pre-Operative Checklist",
  "Radiology Request Form (Outside)",
  "Random Blood Sugar",
  "Refusal to Treatment and Procedure Form",
  "Request for Blood Compatibility Testing Form",
  "Special Endorsements (Transient)",
  "Sponge Count Sheet",
  "Surgical Memorandum",
  "Surgical Memorandum Umbi Cat",
  "Surgical Safety Checklist",
  "TPR Sheet",
];

export function buildFallbackForms() {
  return FORM_CATALOG.map((description, index) => ({
    id: `fallback-${index + 1}`,
    description,
    component_name: description,
    is_active: true,
    fallback: true,
  }));
}
