import "./Forms2.css";

export default function Forms2() {
	return (
		<div className="aldrete-page">
			<div className="aldrete-header-spacer" aria-hidden="true" />

			<div className="aldrete-meta-row">
				<div className="aldrete-meta-pair">
					<span className="aldrete-label">Case Number:</span>
					<span>ADM-2026-010617</span>
				</div>
			</div>

			<div className="aldrete-meta-row">
				<div className="aldrete-meta-pair aldrte-name-pair">
					<span className="aldrete-label">Name of Patient:</span>
					<span>MATILOS , EUGENIA MAMBA</span>
				</div>
				<div className="aldrete-meta-pair">
					<span className="aldrete-label">Age:</span>
					<span>67 year(s)</span>
				</div>
				<div className="aldrete-meta-pair">
					<span className="aldrete-label">Sex:</span>
					<span>F</span>
				</div>
			</div>

			<div className="aldrete-meta-row">
				<div className="aldrete-meta-pair">
					<span className="aldrete-label">ROOM:</span>
					<span>EMERGENCY WARD - ER - ADMISSION - BED 03</span>
				</div>
			</div>

			<p className="aldrete-note">*Patient discharged when the score is 10</p>

			<table className="aldrete-table" aria-label="Aldrete score form table">
				<thead>
					<tr>
						<th>&nbsp;</th>
						<th className="aldrete-points-header">Point Value</th>
					</tr>
				</thead>
				<tbody>
					<tr className="aldrete-section-row">
						<td>COLOR</td>
						<td>&nbsp;</td>
					</tr>
					<tr>
						<td className="aldrete-item">Pink</td>
						<td className="aldrete-point">2</td>
					</tr>
					<tr>
						<td className="aldrete-item">Pale/dusky</td>
						<td className="aldrete-point">1</td>
					</tr>
					<tr>
						<td className="aldrete-item">Cyanotic</td>
						<td className="aldrete-point">0</td>
					</tr>

					<tr className="aldrete-section-row">
						<td>RESPIRATION</td>
						<td>&nbsp;</td>
					</tr>
					<tr>
						<td className="aldrete-item">Can breathe deeply</td>
						<td className="aldrete-point">2</td>
					</tr>
					<tr>
						<td className="aldrete-item">Shallow but adequate</td>
						<td className="aldrete-point">1</td>
					</tr>
					<tr>
						<td className="aldrete-item">Apnea or obstruction</td>
						<td className="aldrete-point">0</td>
					</tr>

					<tr className="aldrete-section-row">
						<td>CIRCULATION</td>
						<td>&nbsp;</td>
					</tr>
					<tr>
						<td className="aldrete-item">Bp within 20% of normal</td>
						<td className="aldrete-point">2</td>
					</tr>
					<tr>
						<td className="aldrete-item">Bp within 21-50% of normal</td>
						<td className="aldrete-point">1</td>
					</tr>
					<tr>
						<td className="aldrete-item">Bp within &gt;50% of normal</td>
						<td className="aldrete-point">0</td>
					</tr>

					<tr className="aldrete-section-row">
						<td>CONSCIOUSNESS</td>
						<td>&nbsp;</td>
					</tr>
					<tr>
						<td className="aldrete-item">Awake, alert and oriented</td>
						<td className="aldrete-point">2</td>
					</tr>
					<tr>
						<td className="aldrete-item">Arousable but readily back to sleep</td>
						<td className="aldrete-point">1</td>
					</tr>
					<tr>
						<td className="aldrete-item">No response</td>
						<td className="aldrete-point">0</td>
					</tr>

					<tr className="aldrete-section-row">
						<td>ACTIVITY</td>
						<td>&nbsp;</td>
					</tr>
					<tr>
						<td className="aldrete-item">Moves all extremities</td>
						<td className="aldrete-point">2</td>
					</tr>
					<tr>
						<td className="aldrete-item">Moves two extremities</td>
						<td className="aldrete-point">1</td>
					</tr>
					<tr>
						<td className="aldrete-item">No movement</td>
						<td className="aldrete-point">0</td>
					</tr>

					<tr className="aldrete-total-row">
						<td>Total</td>
						<td>&nbsp;</td>
					</tr>
				</tbody>
			</table>

			<div className="aldrete-signature-wrap">
				<div className="aldrete-signature-line" aria-hidden="true" />
				<p className="aldrete-signature-name">Signature over Printed Name of PACU Nurse</p>
				<p className="aldrete-signature-date">Date: April 21, 2026 Time: 08:51 AM</p>
			</div>

			<div className="aldrete-default-footer">
				Generated by: TCP T. TCP on 2026-04-21 08:51 AM
			</div>
		</div>
	);
}
