import { useMemo } from "react";
import "./HistopathologyCytology.css";

export default function HistopathologyCytology({ patientName, patientData }) {
  const name      = patientName            || "BAYSA , BABY BOY";
  const caseNo    = patientData?.caseNo    || "ADM-2026-010651";
  const address   = patientData?.address   || "P10, DOÑA TELESFORA, TUBAY, AGUSAN DEL NORTE";
  const age       = patientData?.age       || "1 hour(s)";
  const sex       = patientData?.sex       || "M";
  const physician = patientData?.physician || "";

  const { dateStr, generatedOn } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const h = now.getHours();
    const m = now.getMinutes();
    const ampm = h >= 12 ? "pm" : "am";
    const hh = String(h % 12 || 12).padStart(2, "0");
    const dateStr = now.toLocaleDateString("en-US", {
      year: "numeric", month: "long", day: "numeric",
    });
    const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(m)} ${ampm}`;
    return { dateStr, generatedOn };
  }, []);

  const specRows = [
    "Name of Specimen:",
    "Date & Time collected:",
    "Pre-Operative DX:",
    "Procedure:",
    "Post-Operative DX:",
  ];

  return (
    <div className="hcr-page">
      <br />
      <table className="hcr-info-table">
        <tbody>
          <tr>
            <td colSpan={6} style={{ border: "none", padding: "1.5mm 2mm", fontWeight: "bold" }}>
              Case Number:&nbsp;&nbsp;{caseNo}
            </td>
          </tr>
          {/* Row 2: Name | Date */}
          <tr>
            <th style={{ width: "18mm" }}>NAME:</th>
            <td style={{ width: "55mm" }}>{name}</td>
            <th style={{ width: "14mm" }}>Date:</th>
            <td colSpan={3}>{dateStr}</td>
          </tr>
          {/* Row 3: Address | Age | Sex — Age and Sex in separate cells */}
          <tr>
            <th>ADDRESS:</th>
            <td>{address}</td>
            <th style={{ width: "12mm" }}>Age:</th>
            <td style={{ width: "20mm" }}>{age}</td>
            <th style={{ width: "12mm" }}>Sex:</th>
            <td style={{ width: "10mm" }}>{sex}</td>
          </tr>
          {/* Row 4: Attending Physician */}
          <tr>
            <th style={{ whiteSpace: "nowrap" }}>ATTENDING PHYSICIAN:</th>
            <td colSpan={5}>{physician}</td>
          </tr>
        </tbody>
      </table>

      {/* ── Specimen Details Table ── */}
      <table className="hcr-spec-table">
        <tbody>
          {specRows.map((label, i) => (
            <tr key={i}>
              <td className="hcr-spec-label">{label}</td>
              <td></td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* ── Bottom: checklist (left) + signature (right) ── */}
      <div className="hcr-bottom">

        {/* LEFT: checklist */}
        <div className="hcr-left">
          <div className="hcr-check-title">Please check needed laboratories</div>
          <div className="hcr-item">[ ] ROUTINE HISTOPATH</div>
          <div className="hcr-item">[ ] FROZEN SECTION BIOPSY</div>
          <div className="hcr-item">[ ] CELL BLOCK/FNAB</div>
          <div className="hcr-item">[ ] PAP'S STAIN</div>
          <div className="hcr-others-row">
            <span>[ ] OTHERS:</span>
            <span className="hcr-others-line" />
          </div>
          <div className="hcr-date-row">
            <span>DATE RECEIVED:</span>
            <span>{dateStr}</span>
          </div>
          <div className="hcr-received-row">
            <span>RECEIVED BY:</span>
            <span className="hcr-field-line" />
          </div>
        </div>

        {/* RIGHT: signature */}
        <div className="hcr-right">
          <div className="hcr-prepared-label">Prepared/Requested by:</div>
          <div className="hcr-sig-line" />
          <div className="hcr-sig-label">Signature over Printed Name</div>
          <div className="hcr-license-row">
            <span>License #:</span>
            <span className="hcr-license-line" />
          </div>
        </div>

      </div>

      {/* ── Footer ── */}
      <div className="hcr-footer">
        Generated by: TCP T. TCP on {generatedOn}
      </div>

    </div>
  );
}