import { useMemo } from "react";
import "./IntakeOutputSheet.css";

export default function IntakeOutputSheet({ patientName, patientData }) {
	const name       = patientName;
	const sex        = patientData?.sex;
	const age        = patientData?.age;
	const caseNum    = patientData?.caseNum;
	const hospitalNo = patientData?.hospitalNo;

	const { generatedOn } = useMemo(() => {
		const now = new Date();
		const pad = (n) => String(n).padStart(2, "0");
		const h = now.getHours();
		const m = now.getMinutes();
		const ampm = h >= 12 ? "am" : "am";
		const hh = String(h % 12 || 12).padStart(2, "0");
		const timeStr = `${hh}:${pad(m)} ${ampm}`;
		const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${timeStr}`;
		return { generatedOn };
	}, []);

	const IOTable = () => (
		<table className="ios-table">
			<thead>
				<tr>
					<th className="ios-th ios-col-date" rowSpan={2}>Date:</th>
					<th className="ios-th ios-group-header" colSpan={4}>INTAKE</th>
					<th className="ios-th ios-group-header" colSpan={3}>OUTPUT</th>
					<th className="ios-th ios-col-sig" rowSpan={2}>SIGNATURE</th>
				</tr>
				<tr>
					<th className="ios-th ios-sub">P.O</th>
					<th className="ios-th ios-sub">NGT/OGT</th>
					<th className="ios-th ios-sub">IVF</th>
					<th className="ios-th ios-sub ios-total-sub">TOTAL:</th>
					<th className="ios-th ios-sub">URINE</th>
					<th className="ios-th ios-sub ios-output-blank"></th>
					<th className="ios-th ios-sub ios-total-sub">TOTAL</th>
				</tr>
			</thead>
			<tbody>
				{[
					{ label1: "12-8", label2: "SHIFT" },
					{ label1: "8-4",  label2: "SHIFT" },
					{ label1: "4-12", label2: "SHIFT" },
				].map((shift, i) => (
					<>
						<tr key={`${i}-a`} className="ios-tr ios-tr-shift-top">
							<td className="ios-td ios-shift-label">{shift.label1}</td>
							<td className="ios-td" /><td className="ios-td" /><td className="ios-td" />
							<td className="ios-td" /><td className="ios-td" /><td className="ios-td" />
							<td className="ios-td" /><td className="ios-td" />
						</tr>
						<tr key={`${i}-b`} className="ios-tr ios-tr-shift-bot">
							<td className="ios-td ios-shift-label">{shift.label2}</td>
							<td className="ios-td" /><td className="ios-td" /><td className="ios-td" />
							<td className="ios-td" /><td className="ios-td" /><td className="ios-td" />
							<td className="ios-td" /><td className="ios-td" />
						</tr>
					</>
				))}
				<tr className="ios-tr-total">
					<td className="ios-td ios-total-label" colSpan={5}>TOTAL FOR 24H</td>
					<td className="ios-td ios-total-label" colSpan={3}>TOTAL FOR 24H</td>
					<td className="ios-td" />
				</tr>
			</tbody>
		</table>
	);

	return (
		<div className="ios-page">

			{/* ── Patient info — TOP ── */}
			<div className="ios-patient-strip">
				<div className="ios-strip-row">
					<span className="ios-lbl">Case Number:</span>
					<span className="ios-val">&nbsp;&nbsp;{caseNum}</span>
				</div>
				<div className="ios-strip-row">
					<span className="ios-lbl">Hospital No.:</span>
					<span className="ios-val">&nbsp;&nbsp;{hospitalNo}</span>
				</div>
				<div className="ios-strip-row ios-strip-inline">
					<div>
						<span className="ios-lbl">Patient Name:</span>
						<span className="ios-val">&nbsp;{name}</span>
					</div>
					<div>
						<span className="ios-lbl">Sex:</span>
						<span className="ios-val">&nbsp;{sex}</span>
					</div>
					<div>
						<span className="ios-lbl">Age:</span>
						<span className="ios-val">&nbsp;{age}</span>
					</div>
				</div>
			</div>

			{/* ── 4 identical IO table blocks ── */}
			<div className="ios-tables">
				<IOTable />
				<IOTable />
				<IOTable />
				<IOTable />
			</div>

			{/* ── Footer ── */}
			<div className="ios-footer form-footer">
				Generated by: TCP T. TCP on {generatedOn}
			</div>

		</div>
	);
}