import { useMemo } from "react";
import "./IsolationRecommendation.css";

export default function IsolationRecommendation({ patientName, patientData }) {
	const name = patientName        || "BAYSA , BABY BOY";
	const age  = patientData?.age   || "1 hour(s)";
	const sex  = patientData?.sex   || "M";

	const { dateStr, issuedStr, generatedOn } = useMemo(() => {
		const now = new Date();
		const pad = (n) => String(n).padStart(2, "0");
		const h = now.getHours();
		const m = now.getMinutes();
		const ampm = h >= 12 ? "pm" : "am";
		const hh = String(h % 12 || 12).padStart(2, "0");
		const timeStr = `${hh}:${pad(m)} ${ampm}`;

		const y   = now.getFullYear();
		const mo  = pad(now.getMonth() + 1);
		const d   = pad(now.getDate());
		const day = now.getDate();

		// ordinal suffix
		const ordinal = (n) => {
			const s = ["th","st","nd","rd"];
			const v = n % 100;
			return n + (s[(v - 20) % 10] || s[v] || s[0]);
		};

		const monthName = now.toLocaleDateString("en-US", { month: "long" });
		const dateStr   = `${y}-${mo}-${d}`;
		const issuedStr = `${ordinal(day)} of ${monthName}, ${y}`;
		const generatedOn = `${y}-${mo}-${d} ${timeStr}`;
		return { dateStr, issuedStr, generatedOn };
	}, []);

	const UL = ({ width = "120px" }) => (
		<span className="ir-ul" style={{ width }} />
	);

	return (
		<div className="ir-page">

			{/* ── Opening line ── */}
			<p className="ir-opening">
				This is to certify that Dr.&nbsp;<UL width="180px" />&nbsp;a licensed physician at{" "}
				<strong>AGUSAN DEL NORTE PROVINCIAL HOSPITAL,</strong> recommends that:
			</p>

			{/* ── Patient details ── */}
			<p className="ir-field">
				<strong>Patient Name:</strong> {name}
			</p>

			<p className="ir-field">
				<strong>Age:</strong> {age}
			</p>

			<p className="ir-field">
				<strong>Sex:</strong> {sex}
			</p>

			<p className="ir-field">
				<strong>Date of Consulatation:</strong> {dateStr}
			</p>

			{/* ── Body paragraphs ── */}
			<p className="ir-body">
				be placed in a <strong>private room for isolation purposes.</strong>
			</p>

			<p className="ir-body">
				This recommendation is made based on the patient's current medical condition which requires minimized exposure to other individuals for both the protection of the patient and the general public. 
                This is in accordance with medical protocols. for isolation and infection control.
			</p>

			<p className="ir-body">
				This certification is issued upon the request of the patient or guardian for appropriate documentation and further processing.
			</p>

			<p className="ir-body">
				Issued this {issuedStr} at Agusan del Norte Provincial Hospital, Libertad, Butuan City.
			</p>

			{/* ── Physician + License No ── */}
			<div className="ir-sig-field">
				<span className="ir-sig-lbl"><strong>Physician:</strong></span>
				<UL width="150px" />
			</div>

			<div className="ir-sig-field">
				<span className="ir-sig-lbl"><strong>License No:</strong></span>
				<UL width="150px" />
			</div>

			{/* ── Footer ── */}
			<div className="ir-footer form-footer">
				Generated by: TCP T. TCP on {generatedOn}
			</div>

		</div>
	);
}