import { useMemo } from "react";
import "./IVFSheet.css";

export default function IVFSheet({ patientName, patientData }) {
  const name       = patientName            || "BAYSA , BABY BOY";
  const hospitalNo = patientData?.hospitalNo || "000000000021041";
  const sex        = patientData?.sex       || "M";
  const age        = patientData?.age       || "0";
  const caseNo     = patientData?.caseNo    || "ADM-2026-010651";

  const { generatedOn } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const h = now.getHours();
    const m = now.getMinutes();
    const hh = String(h % 12 || 12).padStart(2, "0");
    const ampm = h < 12 ? "am" : "pm";
    const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(m)} ${ampm}`;
    return { generatedOn };
  }, []);

  const ROWS = 23;

  const headers = [
    { label: "Date",              cls: "ivf-col-date"    },
    { label: "BOT. NO.",          cls: "ivf-col-bot"     },
    { label: "NAME OF IVF",       cls: "ivf-col-name"    },
    { label: "INCORPO-\nRATION",  cls: "ivf-col-incorp"  },
    { label: "FLOW RATE",         cls: "ivf-col-flow"    },
    { label: "TIME",              cls: "ivf-col-time"    },
    { label: "REMARKS",           cls: "ivf-col-remarks" },
    { label: "SIGNATURE",         cls: "ivf-col-sig"     },
  ];

  return (
    <div className="ivf-page">
      <br />
      <table className="ivf-table">
        <colgroup>
          {headers.map((h, i) => (
            <col key={i} className={h.cls} />
          ))}
        </colgroup>
        <thead>
          <tr>
            {headers.map((h, i) => (
              <th key={i}>
                {h.label.split("\n").map((line, j) => (
                  <span key={j}>{line}{j < h.label.split("\n").length - 1 && <br />}</span>
                ))}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {Array.from({ length: ROWS }).map((_, i) => (
            <tr key={i}>
              {headers.map((_, j) => <td key={j} />)}
            </tr>
          ))}
        </tbody>
      </table>

      {/* ── Patient info ── */}
      <div className="ivf-patient-info">
        <div className="ivf-info-row">
          <span className="ivf-info-label">Hospital No.:</span>
          <span className="ivf-info-value">{hospitalNo}</span>
        </div>
        <div className="ivf-info-row">
          <span className="ivf-info-label">Patient Name:</span>
          <span className="ivf-info-value">{name}</span>
        </div>
        <div className="ivf-info-row">
          <span className="ivf-info-label">Sex:</span>
          <span className="ivf-info-value">{sex}</span>
        </div>
        <div className="ivf-info-row">
          <span className="ivf-info-label">Age:</span>
          <span className="ivf-info-value">{age}</span>
        </div>
        <div className="ivf-info-row">
          <span className="ivf-info-label">Case Number:</span>
          <span className="ivf-info-value">&nbsp;&nbsp;{caseNo}</span>
        </div>
      </div>

      {/* ── Footer ── */}
      <div className="ivf-footer">
        Generated by: TCP T. TCP on {generatedOn}
      </div>

    </div>
  );
}