import { useMemo } from "react";
import "./KardexSheet.css";

const KardexTable = () => (
  <table className="kardex-table">
    <thead>
      <tr>
        <th className="kardex-col-date">Date</th>
        <th className="kardex-col-treatment">TREATMENT/<br />PROCEDURE</th>
        <th className="kardex-col-diag">DIAGNOSTICS<br />RADIOLOGY AND LABORATORY</th>
        <th className="kardex-col-iv">INTRAVENOUS FLUIDS/ BLOOD<br />INFUSION</th>
        <th className="kardex-col-diet">DIET</th>
      </tr>
    </thead>
    <tbody>
      {Array.from({ length: 11 }).map((_, i) => (
        <tr key={i}>
          <td className="kardex-col-date" />
          <td className="kardex-col-treatment" />
          <td className="kardex-col-diag" />
          <td className="kardex-col-iv" />
          <td className="kardex-col-diet" />
        </tr>
      ))}
    </tbody>
  </table>
);

export default function KardexSheet({ patientName, patientData }) {
  const name       = patientName            || "BAYSA , BABY BOY";
  const caseNo     = patientData?.caseNo    || "ADM-2026-010651";
  const age        = patientData?.age       || "1";
  const ageUnit    = patientData?.ageUnit   || "hour(s)";
  const sex        = patientData?.sex       || "M";
  const diagnosis  = patientData?.diagnosis || "TERM MALE NEONATE DELIVERED NSVD";
  const cc         = patientData?.cc        || "CEPHALIC WITH AS 8,9 BS 40 WEEKS, BW 3.8 KGS, AGA";
  const room       = patientData?.room      || "OB GYNE - OB 2 - BED 03 - NB";

  const { generatedOn } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const h = now.getHours();
    const m = now.getMinutes();
    const ampm = h >= 12 ? "am" : "am";
    const hh = String(h % 12 || 12).padStart(2, "0");
    const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(m)} ${ampm}`;
    return { generatedOn };
  }, []);

  return (
    <div className="kardex-page">

      {/* ── Header ── */}
      <div className="kardex-header">

        {/* Row 1: Case Number (left) | Age + Sex (right) */}
        <div className="kardex-header-row">
          <div className="kardex-field">
            <span className="kardex-field-label">Case Number:</span>
            <span>{caseNo}</span>
          </div>
          <div className="kardex-header-right">
            <span><strong>Age:</strong> {age} {ageUnit}&nbsp;&nbsp;&nbsp;<strong>Sex:</strong> {sex}</span>
            <br />
            <span>{diagnosis}</span>
          </div>
        </div>

        {/* Row 2: Name (left) | CC (right, continues) */}
        <div className="kardex-header-row">
          <div className="kardex-field">
            <span className="kardex-field-label">Name of Patient:</span>
            <span>{name}</span>
          </div>
          <div className="kardex-header-right">
            <span><strong>CC:</strong> {cc}</span>
          </div>
        </div>

        {/* Row 3: Room */}
        <div className="kardex-room-row">
          <div className="kardex-room-left">
            <span className="kardex-field-label">ROOM:</span>
            <span>{room}</span>
          </div>
        </div>

      </div>

      {/* ── Table 1 ── */}
      <KardexTable />

      {/* ── Table 2 ── */}
      <KardexTable />

      {/* ── Footer ── */}
      <div className="kardex-footer form-footer">
        Generated by: TCP T. TCP on {generatedOn}
      </div>

    </div>
  );
}