import { useMemo } from "react";
import "./KardexSheet.css";

const KardexTable = () => (
  <table className="kardex-table">
    <thead>
      <tr>
        <th className="kardex-col-date">Date</th>
        <th className="kardex-col-treatment">TREATMENT/<br />PROCEDURE</th>
        <th className="kardex-col-diag">DIAGNOSTICS<br />RADIOLOGY AND LABORATORY</th>
        <th className="kardex-col-iv">INTRAVENOUS FLUIDS/ BLOOD<br />INFUSION</th>
        <th className="kardex-col-diet">DIET</th>
      </tr>
    </thead>
    <tbody>
      {Array.from({ length: 6 }).map((_, i) => (
        <tr key={i}>
          <td className="kardex-col-date" />
          <td className="kardex-col-treatment" />
          <td className="kardex-col-diag" />
          <td className="kardex-col-iv" />
          <td className="kardex-col-diet" />
        </tr>
      ))}
    </tbody>
  </table>
);

export default function KardexSheet({ patientName, patientData }) {
  const name      = patientName            || "AMARAH N/A ORTIZ";
  const caseNo    = patientData?.caseNo    || "ADM-2026-010651";
  const age       = patientData?.age       || "1";
  const ageUnit   = patientData?.ageUnit   || "hour(s)";
  const sex       = patientData?.sex       || "M";
  const diagnosis = patientData?.diagnosis || "TERM MALE NEONATE DELIVERED NSVD";
  const cc        = patientData?.cc        || "CEPHALIC WITH AS 8,9 BS 40 WEEKS, BW 3.8 KGS, AGA";
  const room      = patientData?.room      || "OB GYNE - OB 2 - BED 03 - NB";

  const { generatedOn } = useMemo(() => {
    const now  = new Date();
    const pad  = (n) => String(n).padStart(2, "0");
    const h    = now.getHours();
    const m    = now.getMinutes();
    const ampm = h >= 12 ? "pm" : "am";
    const hh   = String(h % 12 || 12).padStart(2, "0");
    return {
      generatedOn: `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(m)} ${ampm}`,
    };
  }, []);

  return (
    <div className="kardex-page">
      <div className="kardex-header">
        <div className="kardex-row-caseno">
          <span className="kardex-lbl">Case Number:</span>
          <span>{caseNo}</span>
        </div>

        {/* Row 2: Name (left) | Age + Sex + Diagnosis (right) */}
        <div className="kardex-row-name">
          <div className="kardex-name-left">
            <span className="kardex-lbl">Name of Patient:</span>
            <span>{name}</span>
          </div>
          <div className="kardex-name-right">
            <div><strong>Age:</strong> {age} {ageUnit}&nbsp;&nbsp;<strong>Sex:</strong> {sex}</div>
            <div>{diagnosis}</div>
          </div>
        </div>

        {/* Row 3: Room (left) | CC (right) */}
        <div className="kardex-row-room">
          <div className="kardex-room-left">
            <span className="kardex-lbl">ROOM:</span>
            <span>{room}</span>
          </div>
          <div className="kardex-room-right">
            <strong>CC:</strong> {cc}
          </div>
        </div>

      </div>

      {/* ── Tables ── */}
      <KardexTable />
      <KardexTable />

      {/* ── Footer ── */}
      <div className="kardex-footer">
        <div className="kardex-footer-line" />
        <div className="kardex-footer-text">Generated by: TCP T. TCP on {generatedOn}</div>
      </div>

    </div>
  );
}