import { useMemo } from "react";
import "./LaboratoryResults.css";

export default function LaboratoryResults({ patientName, patientData }) {
  const name     = patientName            || "FELISELDA , CIAN REIN BAYSA";
  const caseNo   = patientData?.caseNo    || "ADM-2026-010651";
  const hospNo   = patientData?.hospitalNo|| "000000000021041";
  const sex      = patientData?.sex       || "M";
  const age      = patientData?.age       || "1 hour(s)";

  const { generatedOn } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const h = now.getHours();
    const m = now.getMinutes();
    const ampm = h >= 12 ? "pm" : "am";
    const hh = String(h % 12 || 12).padStart(2, "0");
    const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(m)} ${ampm}`;
    return { generatedOn };
  }, []);

  const infoFields = [
    { label: "Case No.",       value: caseNo },
    { label: "Hospital No.",   value: hospNo },
    { label: "Patient's Name", value: name   },
    { label: "Sex",            value: sex    },
    { label: "Age",            value: age    },
  ];

  return (
    <div className="lr-page">

      {/* ── Lines table: 25 empty rows ── */}
      <table className="lr-lines-table">
        <tbody>
          {Array.from({ length: 25 }).map((_, i) => (
            <tr key={i}>
              <td />
            </tr>
          ))}
        </tbody>
      </table>

      {/* ── Attach label ── */}
      <div className="lr-attach-label">
        (ATTACH LABORATORY RESULTS CHRONOLOGICALLY)
      </div>

      {/* ── Patient info ── */}
      <div className="lr-info-block">
        {infoFields.map((f, i) => (
          <div key={i} className="lr-info-row">
            <span className="lr-info-label">{f.label}</span>
            <span className="lr-info-colon">:</span>
            <span className="lr-info-value">{f.value}</span>
          </div>
        ))}
      </div>

      {/* ── Footer ── */}
      <div className="lr-footer">
        Generated by: TCP T. TCP on {generatedOn}
      </div>

    </div>
  );
}