import './Lubchenco.css';
import chartPlaceholderSrc from './img/lubchenco chart.png';

const Lubchenco = () => {
  return (
    <div className="lubchenco-root">
      <div className="lubchenco-page">
        <br />
        <section className="lubchenco-header" aria-label="Form title and patient details">
          <div className="lubchenco-case-number">
            <span className="lubchenco-case-label">Case Number:</span>
            <span className="lubchenco-case-value">ADM-2026-010651</span>
          </div>

          <div className="lubchenco-table">
            <div className="lubchenco-table-row">
              <div className="lubchenco-table-cell">
                <span className="lubchenco-label">Name of Patient:</span>
                <span className="lubchenco-value">FELISELDA , CIAN REIN BAYSA</span>
              </div>
              <div className="lubchenco-table-cell">
                <span className="lubchenco-label">Hospital No.:</span>
                <span className="lubchenco-value">000000000021041</span>
              </div>
            </div>
            <div className="lubchenco-table-row">
              <div className="lubchenco-table-cell">
                <span className="lubchenco-label">Date of Birth:</span>
                <span className="lubchenco-value">April 22, 2026</span>
              </div>
              <div className="lubchenco-table-cell">
                <span className="lubchenco-label">Time of Birth:</span>
                <span className="lubchenco-value">04:10 AM</span>
              </div>
            </div>
          </div>

          <div className="lubchenco-subtitle">
            Classification of newborns (both sexes) by intrauterine growth and gestational age
          </div>
        </section>

        {/* ── CHART — fills all remaining vertical space ── */}
        <section className="lubchenco-chart-section" aria-label="Lubchenco chart">
          <img
            src={chartPlaceholderSrc}
            alt="Lubchenco growth chart"
            className="lubchenco-chart-image"
          />
        </section>

        {/* ── SIGNATURE ── */}
        <br />
        <br />
        <br />
        <div className="lubchenco-signature">
          <div className="lubchenco-signature-line"></div>
          <div className="lubchenco-signature-label">PEDIATRICIAN</div>
        </div>

        {/* ── FOOTER ── */}
        <div className="lubchenco-footer">
          Generated by: TCP T. TCP on April 22, 2026
        </div>

      </div>
    </div>
  );
};

export default Lubchenco;