import { useMemo } from 'react';
import './Lubchenco.css';
import chartPlaceholderSrc from './img/lubchenco chart.png';

const Lubchenco = ({ patientName, patientData }) => {
  const name = patientName || "FELISELDA , CIAN REIN BAYSA";
  const caseNum = patientData?.caseNum || "ADM-2026-010651";
  const hospitalNo = patientData?.hospitalNo || "000000000021041";
  const dateOfBirth = patientData?.dateOfBirth || "";
  const timeOfBirth = patientData?.timeOfBirth || "";

  const { generatedOn, generatedBy } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const timeStr = now.toLocaleTimeString("en-US", {
      hour: "2-digit", minute: "2-digit", hour12: true,
    }).toLowerCase();
    return {
      generatedOn: `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${timeStr}`,
      generatedBy: "TCP T. TCP"
    };
  }, []);
  return (
    <div className="lubchenco-root">
      <div className="lubchenco-page">
        <br />
        <section className="lubchenco-header" aria-label="Form title and patient details">
          <div className="lubchenco-case-number">
            <span className="lubchenco-case-label">Case Number:</span>
            <span className="lubchenco-case-value">{caseNum}</span>
          </div>

          <div className="lubchenco-table">
            <div className="lubchenco-table-row">
              <div className="lubchenco-table-cell">
                <span className="lubchenco-label">Name of Patient:</span>
                <span className="lubchenco-value">{name}</span>
              </div>
              <div className="lubchenco-table-cell">
                <span className="lubchenco-label">Hospital No.:</span>
                <span className="lubchenco-value">{hospitalNo}</span>
              </div>
            </div>
            <div className="lubchenco-table-row">
              <div className="lubchenco-table-cell">
                <span className="lubchenco-label">Date of Birth:</span>
                <span className="lubchenco-value">{dateOfBirth}</span>
              </div>
              <div className="lubchenco-table-cell">
                <span className="lubchenco-label">Time of Birth:</span>
                <span className="lubchenco-value">{timeOfBirth}</span>
              </div>
            </div>
          </div>

          <div className="lubchenco-subtitle">
            Classification of newborns (both sexes) by intrauterine growth and gestational age
          </div>
        </section>

        {/* ── CHART — fills all remaining vertical space ── */}
        <section className="lubchenco-chart-section" aria-label="Lubchenco chart">
          <img
            src={chartPlaceholderSrc}
            alt="Lubchenco growth chart"
            className="lubchenco-chart-image"
          />
        </section>

        {/* ── SIGNATURE ── */}
        <br />
        <br />
        <br />
        <div className="lubchenco-signature">
          <div className="lubchenco-signature-line"></div>
          <div className="lubchenco-signature-label">PEDIATRICIAN</div>
        </div>

        {/* ── FOOTER ── */}
        <div className="lubchenco-footer">
          Generated by: {generatedBy} on {generatedOn}
        </div>

      </div>
    </div>
  );
};

export default Lubchenco;