import { useMemo } from 'react';
import styles from './Lubchenco.module.css';
import chartPlaceholderSrc from './img/lubchenco chart.png';

const Lubchenco = ({ patientName, patientData }) => {
  const name = patientName || "";
  const caseNum = patientData?.caseNum || "";
  const hospitalNo = patientData?.hospitalNo || "";
  const dateOfBirth = patientData?.dateOfBirth || "";
  const timeOfBirth = patientData?.timeOfBirth || "";

  const { generatedOn, generatedBy } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const timeStr = now.toLocaleTimeString("en-US", {
      hour: "2-digit", minute: "2-digit", hour12: true,
    }).toLowerCase();
    return {
      generatedOn: `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${timeStr}`,
      generatedBy: "TCP T. TCP"
    };
  }, []);
  return (
    <div className={styles.root}>
      <div className={styles.page}>
        <section className={styles.header} aria-label="Form title and patient details">
          <div className={styles.caseNumber}>
            <span className={styles.caseLabel}>Case Number:</span>
            <span className={styles.caseValue}>{caseNum}</span>
          </div>

          <div className={styles.table}>
            <div className={styles.tableRow}>
              <div className={styles.tableCell}>
                <span className={styles.label}>Name of Patient:</span>
                <span className={styles.value}>{name}</span>
              </div>
              <div className={styles.tableCell}>
                <span className={styles.label}>Hospital No.:</span>
                <span className={styles.value}>{hospitalNo}</span>
              </div>
            </div>
            <div className={styles.tableRow}>
              <div className={styles.tableCell}>
                <span className={styles.label}>Date of Birth:</span>
                <span className={styles.value}>{dateOfBirth}</span>
              </div>
              <div className={styles.tableCell}>
                <span className={styles.label}>Time of Birth:</span>
                <span className={styles.value}>{timeOfBirth}</span>
              </div>
            </div>
          </div>

          <div className={styles.subtitle}>
            Classification of newborns (both sexes) by intrauterine growth and gestational age
          </div>
        </section>

        {/* ── CHART — fills all remaining vertical space ── */}
        <section className={styles.chartSection} aria-label="Lubchenco chart">
          <img
            src={chartPlaceholderSrc}
            alt="Lubchenco growth chart"
            className={styles.chartImage}
          />
        </section>

        {/* ── SIGNATURE ── */}
        <div className={styles.signature}>
          <div className={styles.signatureLine}></div>
          <div className={styles.signatureLabel}>PEDIATRICIAN</div>
        </div>

        {/* ── FOOTER ── */}
        <div className={styles.footer}>
          Generated by: {generatedBy} on {generatedOn}
        </div>

      </div>
    </div>
  );
};

export default Lubchenco;