import { useMemo } from "react";
import "./MedicationSheet.css";

export default function MedicationSheet({ patientName, patientData }) {
  const name = patientName;

  const { generatedOn } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const h = now.getHours();
    const m = now.getMinutes();
    const hh = String(h % 12 || 12).padStart(2, "0");
    const ampm = h < 12 ? "am" : "pm";
    const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(m)} ${ampm}`;
    return { generatedOn };
  }, []);

  const DATA_ROWS = 18;
  const DATE_COLS = 7;

  return (
    <div className="ms-page">
      <br />
      <table className="ms-table">
        <thead>
          <tr>
            <td className="ms-th-med" style={{ border: "1px solid #000" }}></td>
            <td style={{ border: "1px solid #000" }}></td>
            <td colSpan={DATE_COLS} className="ms-th-date" style={{ border: "1px solid #000" }}>DATE</td>
          </tr>
          {/* Row 2: MEDICATION ORDER | TIME | date col headers */}
          <tr>
            <th className="ms-th-med">MEDICATION ORDER</th>
            <th className="ms-th-time">TIME</th>
            {Array.from({ length: DATE_COLS }).map((_, i) => (
              <th key={i} className="ms-th-date-col"></th>
            ))}
          </tr>
        </thead>

        <tbody>
          {/* Data rows */}
          {Array.from({ length: DATA_ROWS }).map((_, i) => (
            <tr key={i} className="ms-data-row">
              <td></td>
              <td></td>
              {Array.from({ length: DATE_COLS }).map((_, j) => (
                <td key={j}></td>
              ))}
            </tr>
          ))}

          {/* SHIFT | SPECIMEN SIGNATURES header */}
          <tr className="ms-shift-header">
            <td>SHIFT</td>
            <td colSpan={DATE_COLS + 1}>SPECIMEN SIGNATURES</td>
          </tr>

          {/* DAWN row */}
          <tr className="ms-shift-row">
            <td>DAWN</td>
            <td></td>
            {Array.from({ length: DATE_COLS }).map((_, i) => (
              <td key={i}></td>
            ))}
          </tr>

          {/* AM row */}
          <tr className="ms-shift-row">
            <td>AM</td>
            <td></td>
            {Array.from({ length: DATE_COLS }).map((_, i) => (
              <td key={i}></td>
            ))}
          </tr>

          {/* PM row */}
          <tr className="ms-shift-row">
            <td>PM</td>
            <td></td>
            {Array.from({ length: DATE_COLS }).map((_, i) => (
              <td key={i}></td>
            ))}
          </tr>
        </tbody>
      </table>

      {/* ── Patient info ── */}
      <div className="ms-patient-info">
        <div className="ms-info-row">
          <span className="ms-info-label">Case No.</span>
          <span className="ms-info-colon">:</span>
          <span>ADM-2026-010707</span>
        </div>
        <div className="ms-info-row">
          <span className="ms-info-label">Hospital No.</span>
          <span className="ms-info-colon">:</span>
          <span>000000000021386</span>
        </div>
        <div className="ms-info-row">
          <span className="ms-info-label">Patient's Name</span>
          <span className="ms-info-colon">:</span>
          <span>{name}</span>
        </div>
        <div className="ms-info-row">
          <span className="ms-info-label">Sex</span>
          <span className="ms-info-colon">:</span>
          <span>F</span>
        </div>
        <div className="ms-info-row">
          <span className="ms-info-label">Age</span>
          <span className="ms-info-colon">:</span>
          <span>32 year(s)</span>
        </div>
      </div>

      {/* ── Footer ── */}
      <div className="ms-footer">
        Generated by: TCP T. TCP on {generatedOn}
      </div>

    </div>
  );
}