import { useMemo } from "react";
import "./MonitoringSheet.css";

export default function MonitoringSheet({ patientName, patientData }) {
  const name = patientName || "SALUCANA , NELLY JEAN LOFRANCO";

  const { generatedOn } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const h = now.getHours();
    const m = now.getMinutes();
    const hh = String(h % 12 || 12).padStart(2, "0");
    const ampm = h < 12 ? "am" : "pm";
    const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(m)} ${ampm}`;
    return { generatedOn };
  }, []);

  const ROWS = 26;
  const columns = [
    { label: "Date",      cls: "mon-col-date" },
    { label: "Time",      cls: "mon-col-time" },
    { label: "TEMP",      cls: "mon-col-temp" },
    { label: "BP",        cls: "mon-col-bp"   },
    { label: "PR",        cls: "mon-col-pr"   },
    { label: "RR",        cls: "mon-col-rr"   },
    { label: "O2 SAT",    cls: "mon-col-o2"   },
    { label: "FHT",       cls: "mon-col-fht"  },
    { label: "SIGNATURE", cls: "mon-col-sig"  },
  ];

  return (
    <div className="mon-page">
      <br />
      <div className="mon-header">
        <div className="mon-header-row1">
          <span className="mon-label">Case Number:</span>
          <span className="mon-value">&nbsp;ADM-2026-010707</span>
        </div>
        <div className="mon-header-row2">
          <span className="mon-label">Name of Patient:</span>
          <span className="mon-value">&nbsp;{name}</span>
          <div className="mon-right-info">
            <span><span className="mon-label">Age:</span>&nbsp;32 year(s)</span>
            <span><span className="mon-label">Sex:</span>&nbsp;F</span>
          </div>
        </div>
      </div>

      {/* ── Table ── */}
      <table className="mon-table">
        <thead>
          <tr>
            {columns.map((col, i) => (
              <th key={i} className={col.cls}>{col.label}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {Array.from({ length: ROWS }).map((_, i) => (
            <tr key={i}>
              {columns.map((_, j) => <td key={j} />)}
            </tr>
          ))}
        </tbody>
      </table>

      {/* ── Footer ── */}
      <div className="mon-footer">
        Generated by: TCP T. TCP on {generatedOn}
      </div>
    </div>
  );
}