/**
 * Neurologic - Converted to CSS Module
 * 
 * FIX: Removed global style injection that was causing layout conflicts
 * FIX: Now uses CSS Module for scoped styling
 */

import { useMemo } from 'react';
import chartPlaceholderSrc from './img/neurologic examination.png';
import styles from './Neurologic.module.css';

const Neurological = ({ patientName, patientData }) => {
  const name      = patientName            || "";
  const caseNo    = patientData?.caseNo    || "";
  const age       = patientData?.age       || "";
  const sex       = patientData?.sex       || "";
  const date      = patientData?.date      || new Date().toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric"
  });
  const diagnosis = patientData?.diagnosis || "";

  const { generatedOn, generatedBy } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const timeStr = now.toLocaleTimeString("en-US", {
      hour: "2-digit", minute: "2-digit", hour12: true,
    }).toLowerCase();
    return {
      generatedOn: `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${timeStr}`,
      generatedBy: "TCP T. TCP"
    };
  }, []);

  return (
    <div className={styles.container}>
      <div className={styles.page}>
        <section className={styles.body} aria-label="Form title and patient details">
          <div className={styles.patientHeader}>
            {/* Row 1: Case Number — centered */}
            <div className={`${styles.headerRow} ${styles.headerRow1}`}>
              <span className={styles.headerLabel}>Case Number:</span>
              <span className={styles.headerValue}>{caseNo}</span>
            </div>

            {/* Row 2: Patient Name, Age, Sex — centered */}
            <div className={`${styles.headerRow} ${styles.headerRow2}`}>
              <div className={styles.headerItem}>
                <span className={styles.headerLabel}>Patient's Name :</span>
                <span className={styles.headerValue}>{name}</span>
              </div>
              <div className={`${styles.headerItem} ${styles.headerItemInline}`}>
                <span className={styles.headerLabel}>Age :</span>
                <span className={styles.headerValue}>{age}</span>
              </div>
              <div className={`${styles.headerItem} ${styles.headerItemInline}`}>
                <span className={styles.headerLabel}>Sex :</span>
                <span className={styles.headerValue}>{sex}</span>
              </div>
            </div>

            {/* Row 3: Impression/Diagnosis and Date — centered together */}
            <div className={`${styles.headerRow} ${styles.headerRow3}`}>
              <div className={styles.headerItem}>
                <span className={styles.headerLabel}>Impression/Diagnosis:</span>
              </div>
              <div className={styles.headerItem}>
                <span className={styles.headerLabel}>Date:</span>
                <span className={styles.headerValue}>{date}</span>
              </div>
            </div>

            {/* Row 4 & 5: Diagnosis underlines */}
            <div className={`${styles.headerRow} ${styles.headerRow4}`}>
              <span className={styles.headerUnderlineFull}>{diagnosis}</span>
            </div>
            <div className={`${styles.headerRow} ${styles.headerRow4}`}>
              <span className={styles.headerUnderlineFull}></span>
            </div>

          </div>
        </section>

        <section aria-label="Neuro vital signs chart image" className={styles.chartSection}>
          <img
            src={chartPlaceholderSrc}
            alt="Neuro vital signs status chart placeholder"
            className={styles.chartImage}
          />
        </section>

        <div className={styles.formFooter}>Generated by: {generatedBy} on {generatedOn}</div>
      </div>
    </div>
  );
};

export default Neurological;
