import { useEffect } from 'react';
import './NeuroVitalSignsLessThan.css';
import chartPlaceholderSrc from './img/NEURO VITAL SIGNS STATUS.png';

const patientFields = [
  { label: 'Case Number:', value: 'ADM-2026-010651' },
  { label: 'Hospital No.', value: '00000000021041' },
];

// Injects a <style> tag that clamps html/body/#root during print.
// Cannot be done from a component CSS file because CSS modules/scoped
// styles can't target ancestors. This runs once on mount and cleans up
// on unmount so it never leaks into other pages.
const PRINT_STYLE_ID = 'neuro-print-clamp';

const injectPrintClamp = () => {
  if (document.getElementById(PRINT_STYLE_ID)) return;
  const style = document.createElement('style');
  style.id = PRINT_STYLE_ID;
  style.textContent = `
    @media print {
      @page { size: A4; margin: 0; }
      html, body, #root {
        height: 297mm !important;
        max-height: 297mm !important;
        overflow: hidden !important;
        margin: 0 !important;
        padding: 0 !important;
      }
    }
  `;
  document.head.appendChild(style);
};

const removePrintClamp = () => {
  document.getElementById(PRINT_STYLE_ID)?.remove();
};

const NeuroVitalSignsLessThan = () => {
  useEffect(() => {
    injectPrintClamp();
    return () => removePrintClamp();
  }, []);

  return (
    <div className="neuro-vital-signs-container">
      <div className="neuro-vital-signs">

        <section className="form-intro" aria-label="Form title and patient details">
          <div className="patient-meta patient-meta-grid">

            <div className="meta-row meta-row-left">
              <span className="meta-label">{patientFields[0].label}</span>
              <span className="meta-value meta-value-inline">{patientFields[0].value}</span>
            </div>

            <div className="meta-row meta-row-left">
              <span className="meta-label">{patientFields[1].label}</span>
              <span className="meta-value meta-value-inline">{patientFields[1].value}</span>
            </div>

            <div className="meta-row meta-row-split">
              <div className="meta-left-block">
                <span className="meta-label">NAME OF PATIENT:</span>
                <span className="meta-value meta-value-name">FELISELDA, CIAN REIN BAYSA</span>
              </div>
              <div className="meta-right-block meta-right-physician">
                <span className="meta-label">PHYSICIAN:</span>
                <span className="meta-line-fill" />
              </div>
            </div>

            <div className="meta-row meta-row-left">
              <span className="meta-label">Room: OB GYNE - OB 2 - BED 03 - NB</span>
            </div>

            <div className="meta-row meta-row-split meta-row-age-date">
              <div className="meta-left-block">
                <span className="meta-label">Age:</span>
                <span className="meta-value meta-value-inline">1 hour(s)</span>
              </div>
              <div className="meta-right-block meta-right-physician">
                <span className="meta-label">Date: April 21, 2026</span>
              </div>
            </div>

          </div>
        </section>

        <section className="chart-section" aria-label="Neuro vital signs chart image">
          <img
            src={chartPlaceholderSrc}
            alt="Neuro vital signs status chart"
            className="chart-image"
          />
        </section>

        <div className="form-footer">Generated by: TCP T. TCP on April 22, 2026</div>
      </div>
    </div>
  );
};

export default NeuroVitalSignsLessThan;