import { useMemo } from 'react';
import './Neurologic.css';
import chartPlaceholderSrc from './img/neurologic examination.png';

const chartSectionStyle = {
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  marginBottom: '2mm',
};

const chartImageStyle = {
  width: '100%',
  height: 'auto',
  display: 'block',
  objectFit: 'contain',
};

const Neurological = ({ patientName, patientData, generatedBy = "TCP T. TCP" }) => {
  const name      = patientName            || "FELISELDA , CIAN REIN BAYSA";
  const caseNo    = patientData?.caseNo    || "ADM-2026-010651";
  const age       = patientData?.age       || "1 hour(s)";
  const sex       = patientData?.sex       || "M";
  const date      = patientData?.date      || new Date().toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric"
  });
  const diagnosis = patientData?.diagnosis || "";

  const generatedOn = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const timeStr = now.toLocaleTimeString("en-US", {
      hour: "2-digit", minute: "2-digit", hour12: true,
    }).toLowerCase();
    return `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${timeStr}`;
  }, []);

  return (
    <div className="neuro-vital-signs-container">
      <div className="neuro-vital-signs">
        <section className="form-intro" aria-label="Form title and patient details">
          <div className="patient-header">
            {/* Row 1: Case Number — centered */}
            <div className="header-row header-row-1">
              <span className="header-label">Case Number:</span>
              <span className="header-value">{caseNo}</span>
            </div>

            {/* Row 2: Patient Name, Age, Sex — centered */}
            <div className="header-row header-row-2">
              <div className="header-item">
                <span className="header-label">Patient's Name :</span>
                <span className="header-value">{name}</span>
              </div>
              <div className="header-item header-item-inline">
                <span className="header-label">Age :</span>
                <span className="header-value">{age}</span>
              </div>
              <div className="header-item header-item-inline">
                <span className="header-label">Sex :</span>
                <span className="header-value">{sex}</span>
              </div>
            </div>

            {/* Row 3: Impression/Diagnosis and Date — centered together */}
            <div className="header-row header-row-3">
              <div className="header-item">
                <span className="header-label">Impression/Diagnosis:</span>
              </div>
              <div className="header-item">
                <span className="header-label">Date:</span>
                <span className="header-value">{date}</span>
              </div>
            </div>

            {/* Row 4 & 5: Diagnosis underlines */}
            <div className="header-row header-row-4">
              <span className="header-underline-full">{diagnosis}</span>
            </div>
            <div className="header-row header-row-4">
              <span className="header-underline-full"></span>
            </div>

          </div>
        </section>

        <section aria-label="Neuro vital signs chart image" style={chartSectionStyle}>
          <img
            src={chartPlaceholderSrc}
            alt="Neuro vital signs status chart placeholder"
            style={chartImageStyle}
          />
        </section>

        <div className="form-footer">Generated by: {generatedBy} on {generatedOn}</div>
      </div>
    </div>
  );
};

export default Neurological;