import './Neurologic.css';

import chartPlaceholderSrc from './img/neurologic examination.png';

const chartSectionStyle = {
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  marginBottom: '2mm',
};

const chartImageStyle = {
  width: '100%',
  height: 'auto',
  display: 'block',
  objectFit: 'contain',
};

const Neurological = () => {
  return (
    <div className="neuro-vital-signs-container">
      <div className="neuro-vital-signs">
        <div className="header-reserved-space" aria-hidden="true" />

              <section className="form-intro" aria-label="Form title and patient details">
                  <div className="form-title">NEUROLOGIC EXAMINATION FORM</div>
                  
                  <br></br>
                  <br></br>
          
          <div className="patient-header">
            {/* Row 1: Case Number */}
            <div className="header-row header-row-1">
              <span className="header-label">Case Number:</span>
              <span className="header-value">ADM-2026-010651</span>
            </div>

            {/* Row 2: Patient Name, Age, Sex */}
            <div className="header-row header-row-2">
              <div className="header-item">
                <span className="header-label">Patient's Name :</span>
                <span className="header-value">FELISELDA , CIAN REIN BAYSA</span>
              </div>
              <div className="header-item header-item-inline">
                <span className="header-label">Age :</span>
                <span className="header-value">1 hour(s)</span>
              </div>
              <div className="header-item header-item-inline">
                <span className="header-label">Sex :</span>
                <span className="header-value">M</span>
              </div>
            </div>

            {/* Row 3: Impression/Diagnosis with Date */}
            <div className="header-row header-row-3">
              <div className="header-item header-item-full">
                <span className="header-label">Impression/Diagnosis:</span>
              </div>
              <div className="header-item header-item-full">
                <span className="header-label">Date:</span>
                <span className="header-value">April 22, 2026</span>
              </div>
              
            </div>

            {/* Row 4: Bottom underline */}
                      <div className="header-row header-row-4">
                          <br></br>
                          <span className="header-underline-full"></span>
                      </div>
                      <div className="header-row header-row-4">
                          <br></br>
                          <span className="header-underline-full"></span>
                      </div>
          </div>
        </section>

        <section aria-label="Neuro vital signs chart image" style={chartSectionStyle}>
          <img
            src={chartPlaceholderSrc}
            alt="Neuro vital signs status chart placeholder"
            style={chartImageStyle}
          />
        </section>
        <div className="form-footer"> Generated by: TCP T. TCP on April 22, 2026</div>
      </div>
    </div>
  );
};

export default Neurological;