import './NeuroVitalSignsLessThan.css';
import chartPlaceholderSrc from './img/neurolessthan.png';

const chartSectionStyle = {
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  marginTop: '1mm',
  marginBottom: '2mm',
};

const chartImageStyle = {
  width: '100%',
  height: 'auto',
  display: 'block',
  objectFit: 'fill',
  border: 0,
};

const patientFields = [
  { label: 'Case Number:', value: 'ADM-2026-010651' },
  { label: 'Hospital No.', value: '00000000021041' },
];

const NeuroVitalSignsLessThan = () => {
  return (
    <div className="neuro-vital-signs-container">
      <div className="neuro-vital-signs">
        <section className="form-intro" aria-label="Form title and patient details">
          <div className="patient-meta patient-meta-grid">
            <div className="meta-row meta-row-left">
              <span className="meta-label">{patientFields[0].label}</span>
              <span className="meta-value meta-value-inline">{patientFields[0].value}</span>
            </div>

            <div className="meta-row meta-row-left">
              <span className="meta-label">{patientFields[1].label}</span>
              <span className="meta-value meta-value-inline">{patientFields[1].value}</span>
            </div>

            <div className="meta-row meta-row-split">
              <div className="meta-left-block">
                <span className="meta-label">NAME OF PATIENT:</span>
                <span className="meta-value meta-value-name">FELISELDA, CIAN REIN BAYSA</span>
              </div>
              <div className="meta-right-block meta-right-physician">
                <span className="meta-label">PHYSICIAN:</span>
                <span className="meta-line-fill" />
              </div>
            </div>

            <div className="meta-row meta-row-left">
              <span className="meta-label">Room: OB GYNE - OB 2 - BED 03 - NB</span>
            </div>

            <div className="meta-row meta-row-split meta-row-age-date">
              <div className="meta-left-block">
                <span className="meta-label">Age:</span>
                <span className="meta-value meta-value-inline">1 hour(s)</span>
              </div>
              <div className="meta-right-block meta-right-physician">
                <span className="meta-label">Date: April 21, 2026</span>
             
              </div>
            </div>
          </div>
        </section>

        <section aria-label="Neuro vital signs chart image" style={chartSectionStyle}>
          <img
            src={chartPlaceholderSrc}
            alt="Neuro vital signs status chart placeholder"
            style={chartImageStyle}
          />
        </section>
        <div className="form-footer"> Generated by: TCP T. TCP on April 22, 2026</div>
      </div>
    </div>
  );
};

export default NeuroVitalSignsLessThan;