import { useEffect, useMemo } from 'react';
import './NeuroVitalSignsLessThan.css';
import chartPlaceholderSrc from './img/neurolessthan.png';

const NeuroVitalSignsLessThan = ({ patientName, patientData }) => {
  const caseNum = patientData?.caseNum || "ADM-2026-010651";
  const hospitalNo = patientData?.hospitalNo || "00000000021041";
  const name = patientName || "FELISELDA, CIAN REIN BAYSA";
  const room = patientData?.room || "OB GYNE - OB 2 - BED 03 - NB";
  const age = patientData?.age || "1 hour(s)";
  const date = patientData?.date || "April 21, 2026";

  const patientFields = [
    { label: 'Case Number:', value: caseNum },
    { label: 'Hospital No.', value: hospitalNo },
  ];

  const { generatedOn, generatedBy } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const timeStr = now.toLocaleTimeString("en-US", {
      hour: "2-digit", minute: "2-digit", hour12: true,
    }).toLowerCase();
    return {
      generatedOn: `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${timeStr}`,
      generatedBy: "TCP T. TCP"
    };
  }, []);
  useEffect(() => {
    const style = document.createElement('style');
    style.id = 'nvs-print-clamp';
    style.textContent = `
      @media print {
        @page { size: A4; margin: 0; }
        html, body, #root {
          height: 297mm !important;
          max-height: 297mm !important;
          overflow: hidden !important;
          margin: 0 !important;
          padding: 0 !important;
        }
      }
    `;
    if (!document.getElementById('nvs-print-clamp')) {
      document.head.appendChild(style);
    }
    return () => document.getElementById('nvs-print-clamp')?.remove();
  }, []);

  return (
    <div className="neuro-vital-signs-container">
      <div className="neuro-vital-signs">

        <section className="form-intro" aria-label="Form title and patient details">
          <div className="patient-meta patient-meta-grid">

            <div className="meta-row meta-row-left">
              <span className="meta-label">{patientFields[0].label}</span>
              <span className="meta-value meta-value-inline">{patientFields[0].value}</span>
            </div>

            <div className="meta-row meta-row-left">
              <span className="meta-label">{patientFields[1].label}</span>
              <span className="meta-value meta-value-inline">{patientFields[1].value}</span>
            </div>

            <div className="meta-row meta-row-split">
              <div className="meta-left-block">
                <span className="meta-label">NAME OF PATIENT:</span>
                <span className="meta-value meta-value-name">{name}</span>
              </div>
              <div className="meta-right-block meta-right-physician">
                <span className="meta-label">PHYSICIAN:</span>
                <span className="meta-line-fill" />
              </div>
            </div>

            <div className="meta-row meta-row-left">
              <span className="meta-label">Room: {room}</span>
            </div>

            <div className="meta-row meta-row-split meta-row-age-date">
              <div className="meta-left-block">
                <span className="meta-label">Age:</span>
                <span className="meta-value meta-value-inline">{age}</span>
              </div>
              <div className="meta-right-block meta-right-physician">
                <span className="meta-label">Date: {date}</span>
              </div>
            </div>
          </div>
        </section>

        <section className="chart-section" aria-label="Neuro vital signs chart image">
          <img
            src={chartPlaceholderSrc}
            alt="Neuro vital signs status chart"
            className="chart-image"
          />
        </section>

        <div className="form-footer">Generated by: {generatedBy} on {generatedOn}</div>

      </div>
    </div>
  );
};

export default NeuroVitalSignsLessThan;