import { useMemo } from "react";
import "./NewbornDailyWeightAbdominalGirth.css";

export default function NewbornDailyWeightAbdominalGirth({
  patientName,
  patientData,
}) {
  const caseNumber     = patientData?.caseNumber     || "ADM-2026-010651";
  const hospitalNumber = patientData?.hospitalNumber || "000000000021041";
  const name           = patientName                 || "BAYSA , BABY BOY";
  const dateOfBirth    = patientData?.dateOfBirth    || "";
  const rows           = patientData?.rows           || [];

  const { generatedOn } = useMemo(() => {
    const now  = new Date();
    const pad  = (n) => String(n).padStart(2, "0");
    const h    = now.getHours();
    const hh   = String(h % 12 || 12).padStart(2, "0");
    const ampm = h < 12 ? "am" : "pm";
    return {
      generatedOn: `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(now.getMinutes())} ${ampm}`,
    };
  }, []);

  const ROW_COUNT = 25;
  const tableRows = Array.from({ length: ROW_COUNT }, (_, i) => rows[i] || {});

  return (
    <div className="dwag-page">
      <br />
      <div className="dwag-header">
        <div className="dwag-header-left">
          <div className="dwag-header-row">
            <strong>Case Number:</strong>&nbsp;&nbsp;{caseNumber}
          </div>
          <div className="dwag-header-row">
            <strong>Hospital No.:</strong>&nbsp;&nbsp;{hospitalNumber}
          </div>
        </div>
      </div>

      {/* ── NAME + DOB ── */}
      <div className="dwag-name-row">
        <span><strong>NAME:</strong>&nbsp;{name}</span>
        <span><strong>DATE OF BIRTH</strong>&nbsp;{dateOfBirth}</span>
      </div>

      {/* ── Table ── */}
      <table className="dwag-table">
        <thead>
          <tr>
            <th className="dwag-col-date">DATE</th>
            <th className="dwag-col-weight">WEIGHT (kg.)</th>
            <th className="dwag-col-hc">HEAD CIRCUMFERENCE</th>
            <th className="dwag-col-ac">ABDOMINAL<br />CIRCUMFERENCE</th>
            <th className="dwag-col-nod">NOD</th>
          </tr>
        </thead>
        <tbody>
          {tableRows.map((row, i) => (
            <tr key={i}>
              <td>{row.date                    || ""}</td>
              <td>{row.weight                  || ""}</td>
              <td>{row.headCircumference       || ""}</td>
              <td>{row.abdominalCircumference  || ""}</td>
              <td>{row.nod                     || ""}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* ── Footer ── */}
      <div className="dwag-footer">
        Generated by: TCP T. TCP on {generatedOn}
      </div>

    </div>
  );
}