import { useMemo } from "react";
import "./NewbornTag.css";

export default function NewbornTag({ patientName, patientData }) {
  const name       = patientName             || "BAYSA , BABY BOY";
  const hospitalNo = patientData?.hospitalNo || "000000000021041";
  const weight     = patientData?.weight     || "3800";
  const dob        = patientData?.dob        || "04-22-2026 04:10 AM";

  const { generatedOn } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const h = now.getHours();
    const m = now.getMinutes();
    const ampm = h >= 12 ? "am" : "am";
    const hh = String(h % 12 || 12).padStart(2, "0");
    const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(m)} ${ampm}`;
    return { generatedOn };
  }, []);

  return (
    <div className="nbt-page">

      {/* ── Tag block ── */}
      <div className="nbt-tag-block">
        {/* Left: hospital no, name, DOB */}
        <div className="nbt-tag-left">
          <span className="nbt-hospital-no">{hospitalNo}</span>
          <span className="nbt-patient-name">{name}</span>
          <span className="nbt-db-line">DB: {dob}</span>
        </div>

        {/* Right: Weight */}
        <div className="nbt-tag-right">
          W:{weight}
        </div>
      </div>

      {/* ── Footer ── */}
      <div className="nbt-footer">
        Generated by: TCP T. TCP on {generatedOn}
      </div>

    </div>
  );
}