import { useMemo } from "react";
import "./NursesNotes.css";

export default function NursesNotes({ patientName, patientData }) {
  const caseNumber     = patientData?.caseNumber     || "ADM-2026-010651";
  const hospitalNumber = patientData?.hospitalNumber || "000000000021041";
  const name           = patientName                 || "BAYSA , BABY BOY";
  const sex            = patientData?.sex            || "M";
  const age            = patientData?.age            || "0";
  const room           = patientData?.room           || "OB GYNE - OB 2 - BED 03 - NB";
  const rows           = patientData?.rows           || [];

  const { generatedOn } = useMemo(() => {
    const now  = new Date();
    const pad  = (n) => String(n).padStart(2, "0");
    const h    = now.getHours();
    const hh   = String(h % 12 || 12).padStart(2, "0");
    const ampm = h < 12 ? "am" : "pm";
    return {
      generatedOn: `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(now.getMinutes())} ${ampm}`,
    };
  }, []);

  const ROW_COUNT = 25;
  const tableRows = Array.from({ length: ROW_COUNT }, (_, i) => rows[i] || {});

  return (
    <div className="nn-page">

      {/* ── Title ── */}
      <div className="nn-title">NURSE'S NOTES</div>

      {/* ── Main Table ── */}
      <table className="nn-table">
        <thead>
          <tr>
            <th className="nn-col-date">Date</th>
            <th className="nn-col-time">Time</th>
            <th className="nn-col-focus">Focus</th>
            <th className="nn-col-dar">DAR</th>
          </tr>
        </thead>
        <tbody>
          {tableRows.map((row, i) => (
            <tr key={i}>
              <td>{row.date  || ""}</td>
              <td>{row.time  || ""}</td>
              <td>{row.focus || ""}</td>
              <td>{row.dar   || ""}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* ── Patient Info Block (bottom) ── */}
      <div className="nn-info-block">
        <div><strong>Case No.:</strong> {caseNumber}</div>
        <div><strong>Hospital No.:</strong> {hospitalNumber}</div>
        <div><strong>Patient Name:</strong> {name}</div>
        <div><strong>Sex:</strong> {sex}</div>
        <div><strong>Age:</strong> {age}</div>
        <div><strong>Room No.:</strong> {room}</div>
      </div>

      {/* ── Footer ── */}
      <div className="nn-footer">
        Generated by: TCP T. TCP on {generatedOn}
      </div>

    </div>
  );
}