import { useMemo } from "react";
import "./OxygenConsumptionSheet.css";

export default function OxygenConsumptionSheet({ patientName, patientData }) {
	const name    = patientName          || "PELISCO , BABY GIRL";
	const age     = patientData?.age     || "1 hour(s)";
	const sex     = patientData?.sex     || "F";
	const caseNum = patientData?.caseNum || "ADM-2026-010623";

	const { generatedOn } = useMemo(() => {
		const now = new Date();
		const pad = (n) => String(n).padStart(2, "0");
		const h = now.getHours();
		const m = now.getMinutes();
		const ampm = h >= 12 ? "pm" : "am";
		const hh = String(h % 12 || 12).padStart(2, "0");
		const timeStr = `${hh}:${pad(m)} ${ampm}`;
		const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${timeStr}`;
		return { generatedOn };
	}, []);

	const ROW_COUNT = 30;

	return (
		<div className="ocs-page">

			{/* ── Header info ── */}
			<div className="ocs-header">
				<div className="ocs-header-row">
					<div className="ocs-header-left">
						<span className="ocs-lbl">Case Number:</span>
						<span className="ocs-val">&nbsp;{caseNum}</span>
					</div>
				</div>
				<div className="ocs-header-row">
					<div className="ocs-header-left">
						<span className="ocs-lbl">Name of Patient:</span>
						<span className="ocs-val">&nbsp;&nbsp;&nbsp;&nbsp;{name}</span>
					</div>
					<div className="ocs-header-right">
						<span className="ocs-lbl">Age:</span>
						<span className="ocs-val">&nbsp;&nbsp;{age}</span>
						<span className="ocs-lbl" style={{ marginLeft: "16px" }}>Sex:</span>
						<span className="ocs-val">&nbsp;&nbsp;{sex}</span>
					</div>
				</div>
			</div>

			{/* ── Table ── */}
			<table className="ocs-table">
				<thead>
					<tr>
						<th className="ocs-th ocs-col-date">Date</th>
						<th className="ocs-th ocs-col-shift">Shift</th>
						<th className="ocs-th ocs-col-initial">Initial Reading</th>
						<th className="ocs-th ocs-col-terminal">Terminal Reading</th>
						<th className="ocs-th ocs-col-o2">O2 Consumed</th>
						<th className="ocs-th ocs-col-sig">SIGNATURE</th>
					</tr>
				</thead>
				<tbody>
					{Array.from({ length: ROW_COUNT }).map((_, i) => (
						<tr key={i} className="ocs-tr">
							<td className="ocs-td ocs-col-date" />
							<td className="ocs-td ocs-col-shift" />
							<td className="ocs-td ocs-col-initial" />
							<td className="ocs-td ocs-col-terminal" />
							<td className="ocs-td ocs-col-o2" />
							<td className="ocs-td ocs-col-sig" />
						</tr>
					))}
				</tbody>
			</table>

			{/* ── Footer ── */}
			<div className="ocs-footer form-footer">
				Generated by: TCP T. TCP on {generatedOn}
			</div>

		</div>
	);
}