import { useMemo } from "react";
import "./PagtugotWaiver.css";

export default function PagtugotWaiver({ patientName, patientData }) {
  const name = patientName || "SALUCANA , NELLY JEAN LOFRANCO";

  const { dateStr, generatedOn } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const h = now.getHours();
    const m = now.getMinutes();
    const hh = String(h % 12 || 12).padStart(2, "0");
    const ampm = h < 12 ? "am" : "pm";
    const dateStr = `${pad(now.getMonth() + 1)}-${pad(now.getDate())}-${now.getFullYear()}`;
    const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(m)} ${ampm}`;
    return { dateStr, generatedOn };
  }, []);

  const items = [
    "Wala nay kwarto nga masudlan busa sa hallway na lang iplastar ang pasyente gamit ang hospital folding bed.",
    "Kung wala nay bakante nga folding bed, ang wheel chair/linkuranan o stretcher una sa ward ang gamiton samtang maghulat nga adunay mabakante nga katre/folding bed.",
    "Kung walay bakante nga infant incubator, ang bata iplastar una sa bassinet o lamesa.",
    "Walay bakante/Supply nga medical oxygen.",
    "Walay ICU ang Hospital",
    "Walay neuro-surgeon",
  ];

  return (
    <div className="ptw-page">

      {/* ── Patient info ── */}
      <div className="ptw-patient-info">
        <div className="ptw-info-row">
          <span className="ptw-info-label">Case No.</span>
          <span className="ptw-info-colon">:</span>
          <span>ADM-2026-010707</span>
        </div>
        <div className="ptw-info-row">
          <span className="ptw-info-label">Hospital No.</span>
          <span className="ptw-info-colon">:</span>
          <span>000000000021386</span>
        </div>
        <div className="ptw-info-row">
          <span className="ptw-info-label">Patient's Name</span>
          <span className="ptw-info-colon">:</span>
          <span>{name}</span>
        </div>
        <div className="ptw-info-row">
          <span className="ptw-info-label">Sex</span>
          <span className="ptw-info-colon">:</span>
          <span>F</span>
        </div>
        <div className="ptw-info-row">
          <span className="ptw-info-label">Age</span>
          <span className="ptw-info-colon">:</span>
          <span>32 year(s)</span>
        </div>
      </div>

      {/* ── Opening paragraph ── */}
      <div className="ptw-opening">
        Human &nbsp; sa &nbsp; maayo &nbsp; nga &nbsp; pagpasabot &nbsp; kanako, &nbsp; ako &nbsp; si{" "}
        <span className="ptw-opening-line" /> nga ana sa ensaktong pangidaron
        nagatugot nga ako/akong pasyente masulod/ma-admit diri sa Agusan del Norte
        Provincial Hospital bisan pa sa mga sumusunod na nga sitwasyon:
      </div>

      {/* ── Checkbox items ── */}
      <div className="ptw-items">
        {items.map((item, i) => (
          <div key={i} className="ptw-item">
            <span className="ptw-item-bracket">( )</span>
            <span className="ptw-item-text">{item}</span>
          </div>
        ))}
        <div className="ptw-item">
          <span className="ptw-item-bracket">( )</span>
          <span className="ptw-item-text">
            Uban pa <span className="ptw-uban-line" />.
          </span>
        </div>
      </div>

      {/* ── Closing paragraph ── */}
      <div className="ptw-closing">
        Akong gikuhaan ang mga hospital staff/personnel sa AGUSAN DEL NORTE
        PROVINCIAL HOSPITAL sa unsa mang responsibilidad kung unsa man ugaling ang
        dangatan kanako/akong pasyente sa akong desisyon nga gihimo.
      </div>

      {/* ── Signature section ── */}
      <div className="ptw-sig-section">

        {/* Patient name centered above left signature line */}
        <div className="ptw-sig-row">
          <div className="ptw-sig-left">
            <div className="ptw-sig-name">{name}</div>
            <div className="ptw-sig-line-full" />
          </div>
          <div className="ptw-sig-right">
            <div className="ptw-sig-line-full" />
          </div>
        </div>

        {/* Labels row */}
        <div className="ptw-sig-label-row">
          <div className="ptw-sig-label-left">
            Ngalan ug pirma ibabaw sa pangalan sa nitugot
          </div>
          <div className="ptw-sig-label-right">
            Ngalan ug pirma ibabaw sa pangalan sa testigo
          </div>
        </div>
        <br />
        <br />

        {/* Date centered below both labels */}
        <div className="ptw-date-row">{dateStr}</div>
      </div>

      {/* ── Footer ── */}
      <div className="ptw-footer">
        Generated by: TCP T. TCP on {generatedOn}
      </div>

    </div>
  );
}