import { useMemo } from 'react';
import './Partograph.css';

import chartPlaceholderSrc from './img/PARTOGRAPH.png';

const chartSectionStyle = {
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  marginBottom: '2mm',
};

const chartImageStyle = {
  width: '100%',
  height: '200mm',
  display: 'block',
  objectFit: 'fill',
  border: 0,
};

const Partograph = ({ patientName, patientData }) => {
  const name = patientName || "FELISELDA , CIAN REIN BAYSA";
  const hospitalNo = patientData?.hospitalNo || "000000000021041";
  const caseNo = patientData?.caseNo || "ADM-2026-010651";
  const dateTimeAdmitted = patientData?.dateTimeAdmitted || "2026-04-22 04:10 AM";
  const age = patientData?.age || "1 hour(s)";
  const sex = patientData?.sex || "M";

  const generatedOn = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const timeStr = now.toLocaleTimeString("en-US", {
      hour: "2-digit", minute: "2-digit", hour12: true,
    }).toLowerCase();
    return `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${timeStr}`;
  }, []);

  const generatedBy = "TCP T. TCP";

  return (
    <div className="neuro-vital-signs-container">
      <div className="neuro-vital-signs">
        <div className="header-reserved-space" aria-hidden="true" />
        <section className="form-intro partograph-header" aria-label="Form title and patient details">
          <div className="patient-header partograph-meta">
            <div className="partograph-meta-row partograph-meta-row--top">
              <div className="partograph-meta-item partograph-meta-item--left">
                <span className="header-label">Hospital No.:</span>
                <span className="header-value">{hospitalNo}</span>
              </div>
              <div className="partograph-meta-item partograph-meta-item--center">
                <span className="header-label">Date/Time Admitted:</span>
                <span className="header-value">{dateTimeAdmitted}</span>
              </div>
              <div className="partograph-meta-item partograph-meta-item--right">
                <span className="header-label">Case Number:</span>
                <span className="header-value">{caseNo}</span>
              </div>
            </div>

            <div className="partograph-meta-row partograph-meta-row--patient">
              <div className="partograph-meta-item partograph-meta-item--patient">
                <span className="header-label">Patient Name:</span>
                <span className="header-value">{name}</span>
              </div>
              <div className="partograph-meta-item partograph-meta-item--inline">
                <span className="header-label">Age:</span>
                <span className="header-value">{age}</span>
              </div>
              <div className="partograph-meta-item partograph-meta-item--inline">
                <span className="header-label">Sex:</span>
                <span className="header-value">{sex}</span>
              </div>
            </div>

            <div className="partograph-meta-row partograph-meta-row--blank">
              <div className="partograph-blank-field">
                <span className="header-label">LMP:</span>
                <span className="partograph-blank-line partograph-blank-line--sm" aria-hidden="true" />
              </div>
              <div className="partograph-blank-field">
                <span className="header-label">AOG:</span>
                <span className="partograph-blank-line partograph-blank-line--sm" aria-hidden="true" />
              </div>
              <div className="partograph-blank-field">
                <span className="header-label">EDC:</span>
                <span className="partograph-blank-line partograph-blank-line--sm" aria-hidden="true" />
              </div>
              <div className="partograph-blank-field">
                <span className="header-label">FH:</span>
                <span className="partograph-blank-line partograph-blank-line--xs" aria-hidden="true" />
              </div>
              <div className="partograph-blank-field partograph-blank-field--group">
                <span className="header-label">G__P__</span>
                <span className="partograph-tpal-label">(TPAL)</span>
                <span className="partograph-blank-line partograph-blank-line--xs" aria-hidden="true" />
              </div>
            </div>
          </div>
        </section>

        <section aria-label="Partograph chart image" style={chartSectionStyle}>
          <img
            src={chartPlaceholderSrc}
            alt="Partograph status chart placeholder"
            style={chartImageStyle}
          />
        </section>
        <div className="form-footer">Generated by: {generatedBy} on {generatedOn}</div>
      </div>
    </div>
  );
};

export default Partograph;