import './Partograph.css';

import chartPlaceholderSrc from './img/PARTOGRAPH.png';

const chartSectionStyle = {
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  marginBottom: '2mm',
};

const chartImageStyle = {
  width: '100%',
  height: '200mm',
  display: 'block',
  objectFit: 'fill',
  border: 0,
};

const Partograph = () => {
  return (
    <div className="neuro-vital-signs-container">
      <div className="neuro-vital-signs">
        <div className="header-reserved-space" aria-hidden="true" />

        <section className="form-intro partograph-header" aria-label="Form title and patient details">
          <div className="partograph-title">PARTOGRAPH</div>

          <div className="patient-header partograph-meta">
            <div className="partograph-meta-row partograph-meta-row--top">
              <div className="partograph-meta-item partograph-meta-item--left">
                <span className="header-label">Hospital No.:</span>
                <span className="header-value">000000000021041</span>
              </div>
              <div className="partograph-meta-item partograph-meta-item--center">
                <span className="header-label">Date/Time Admitted:</span>
                <span className="header-value">2026-04-22 04:10 AM</span>
              </div>
              <div className="partograph-meta-item partograph-meta-item--right">
                <span className="header-label">Case Number:</span>
                <span className="header-value">ADM-2026-010651</span>
              </div>
            </div>

            <div className="partograph-meta-row partograph-meta-row--patient">
              <div className="partograph-meta-item partograph-meta-item--patient">
                <span className="header-label">Patient Name:</span>
                <span className="header-value">FELISELDA , CIAN REIN BAYSA</span>
              </div>
              <div className="partograph-meta-item partograph-meta-item--inline">
                <span className="header-label">Age:</span>
                <span className="header-value">1 hour(s)</span>
              </div>
              <div className="partograph-meta-item partograph-meta-item--inline">
                <span className="header-label">Sex:</span>
                <span className="header-value">M</span>
              </div>
            </div>

            <div className="partograph-meta-row partograph-meta-row--blank">
              <div className="partograph-blank-field">
                <span className="header-label">LMP:</span>
                <span className="partograph-blank-line partograph-blank-line--sm" aria-hidden="true" />
              </div>
              <div className="partograph-blank-field">
                <span className="header-label">AOG:</span>
                <span className="partograph-blank-line partograph-blank-line--sm" aria-hidden="true" />
              </div>
              <div className="partograph-blank-field">
                <span className="header-label">EDC:</span>
                <span className="partograph-blank-line partograph-blank-line--sm" aria-hidden="true" />
              </div>
              <div className="partograph-blank-field">
                <span className="header-label">FH:</span>
                <span className="partograph-blank-line partograph-blank-line--xs" aria-hidden="true" />
              </div>
              <div className="partograph-blank-field partograph-blank-field--group">
                <span className="header-label">G__P__</span>
                <span className="partograph-tpal-label">(TPAL)</span>
                <span className="partograph-blank-line partograph-blank-line--xs" aria-hidden="true" />
              </div>
            </div>
          </div>
        </section>

        <section aria-label="Partograph chart image" style={chartSectionStyle}>
          <img
            src={chartPlaceholderSrc}
            alt="Partograph status chart placeholder"
            style={chartImageStyle}
          />
        </section>
        <div className="form-footer"> Generated by: TCP T. TCP on April 22, 2026</div>
      </div>
    </div>
  );
};

export default Partograph;