/**
 * Partograph - Converted to CSS Module
 * 
 * FIX: Removed global style injection that was causing layout conflicts
 * FIX: Now uses CSS Module for scoped styling
 * FIX: Layout optimized to fit within FormDocument wrapper
 */

import { useMemo } from 'react';
import chartPlaceholderSrc from './img/PARTOGRAPH.png';
import styles from './Partograph.module.css';

const Partograph = ({ patientName, patientData }) => {
  const name = patientName || "";
  const hospitalNo = patientData?.hospitalNo || "";
  const caseNo = patientData?.caseNo || "";
  const dateTimeAdmitted = patientData?.dateTimeAdmitted || "";
  const age = patientData?.age || "";
  const sex = patientData?.sex || "";

  const generatedOn = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const timeStr = now.toLocaleTimeString("en-US", {
      hour: "2-digit", minute: "2-digit", hour12: true,
    }).toLowerCase();
    return `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${timeStr}`;
  }, []);

  const generatedBy = "TCP T. TCP";

  return (
    <div className={styles.page}>
      <div className={styles.headerSpace} aria-hidden="true" />
      
      <div className={styles.partographMeta}>
        <div className={`${styles.partographMetaRow} ${styles.partographMetaRowTop}`}>
          <div className={`${styles.partographMetaItem} ${styles.partographMetaItemLeft}`}>
            <span className={styles.headerLabel}>Hospital No.:</span>
            <span className={styles.headerValue}>{hospitalNo}</span>
          </div>
          <div className={`${styles.partographMetaItem} ${styles.partographMetaItemCenter}`}>
            <span className={styles.headerLabel}>Date/Time Admitted:</span>
            <span className={styles.headerValue}>{dateTimeAdmitted}</span>
          </div>
          <div className={`${styles.partographMetaItem} ${styles.partographMetaItemRight}`}>
            <span className={styles.headerLabel}>Case Number:</span>
            <span className={styles.headerValue}>{caseNo}</span>
          </div>
        </div>

        <div className={`${styles.partographMetaRow} ${styles.partographMetaRowPatient}`}>
          <div className={`${styles.partographMetaItem} ${styles.partographMetaItemPatient}`}>
            <span className={styles.headerLabel}>Patient Name:</span>
            <span className={styles.headerValue}>{name}</span>
          </div>
          <div className={`${styles.partographMetaItem} ${styles.partographMetaItemInline}`}>
            <span className={styles.headerLabel}>Age:</span>
            <span className={styles.headerValue}>{age}</span>
          </div>
          <div className={`${styles.partographMetaItem} ${styles.partographMetaItemInline}`}>
            <span className={styles.headerLabel}>Sex:</span>
            <span className={styles.headerValue}>{sex}</span>
          </div>
        </div>

        <div className={`${styles.partographMetaRow} ${styles.partographMetaRowBlank}`}>
          <div className={styles.blankField}>
            <span className={styles.headerLabel}>LMP:</span>
            <span className={`${styles.blankLine} ${styles.blankLineSm}`} aria-hidden="true" />
          </div>
          <div className={styles.blankField}>
            <span className={styles.headerLabel}>AOG:</span>
            <span className={`${styles.blankLine} ${styles.blankLineSm}`} aria-hidden="true" />
          </div>
          <div className={styles.blankField}>
            <span className={styles.headerLabel}>EDC:</span>
            <span className={`${styles.blankLine} ${styles.blankLineSm}`} aria-hidden="true" />
          </div>
          <div className={styles.blankField}>
            <span className={styles.headerLabel}>FH:</span>
            <span className={`${styles.blankLine} ${styles.blankLineXs}`} aria-hidden="true" />
          </div>
          <div className={`${styles.blankField} ${styles.blankFieldGroup}`}>
            <span className={styles.headerLabel}>G__P__</span>
            <span className={styles.tpalLabel}>(TPAL)</span>
            <span className={`${styles.blankLine} ${styles.blankLineXs}`} aria-hidden="true" />
          </div>
        </div>
      </div>

      <div className={styles.chartSection}>
        <img
          src={chartPlaceholderSrc}
          alt="Partograph status chart placeholder"
          className={styles.chartImage}
        />
      </div>
      
      <div className={styles.formFooter}>Generated by: {generatedBy} on {generatedOn}</div>
    </div>
  );
};

export default Partograph;
