import { useMemo } from "react";
import "./PhototherapyForm.css";

export default function PhototherapyForm({ patientName, patientData }) {
  const hospitalNumber = patientData?.hospitalNumber || "000000000021041";
  const caseNumber     = patientData?.caseNumber     || "ADM-2026-010651";
  const name           = patientName                 || "BAYSA , BABY BOY";
  const dateOfBirth    = patientData?.dateOfBirth    || "04:10 AM";
  const rows           = patientData?.rows           || [];

  const { generatedOn } = useMemo(() => {
    const now  = new Date();
    const pad  = (n) => String(n).padStart(2, "0");
    const h    = now.getHours();
    const hh   = String(h % 12 || 12).padStart(2, "0");
    const ampm = h < 12 ? "am" : "pm";
    return {
      generatedOn: `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(now.getMinutes())} ${ampm}`,
    };
  }, []);

  const ROW_COUNT = 25;
  const tableRows = Array.from({ length: ROW_COUNT }, (_, i) => rows[i] || {});

  const TableBlock = () => (
    <table className="pt-table">
      <thead>
        <tr>
          <th className="pt-col-date">DATE</th>
          <th className="pt-col-hours"># OF HOURS</th>
          <th className="pt-col-nod">NOD</th>
        </tr>
      </thead>
      <tbody>
        {tableRows.map((row, i) => (
          <tr key={i}>
            <td>{row.date    || ""}</td>
            <td>{row.hours   || ""}</td>
            <td>{row.nod     || ""}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );

  return (
    <div className="pt-page">

      {/* ── Header ── */}
      <div className="pt-header">
        <div className="pt-header-left">
          <div className="pt-header-row">
            <strong>Hospital No.:</strong>&nbsp;{hospitalNumber}
          </div>
          <div className="pt-header-row">
            <strong>NAME:</strong>&nbsp;{name}
          </div>
        </div>
        <div className="pt-header-mid">
          <div className="pt-header-row">
            <strong>Case Number:</strong>&nbsp;{caseNumber}
          </div>
          <div className="pt-header-row">
            <strong>DATE OF BIRTH:</strong>&nbsp;{dateOfBirth}
          </div>
        </div>
      </div>

      {/* ── Two-column table layout ── */}
      <div className="pt-columns">
        <div className="pt-col-block">
          <TableBlock />
        </div>
        <div className="pt-col-gap" />
        <div className="pt-col-block">
          <TableBlock />
        </div>
      </div>

      {/* ── Footer ── */}
      <div className="pt-footer form-footer">
        Generated by: TCP T. TCP on {generatedOn}
      </div>

    </div>
  );
}