import { useMemo } from 'react';
import './PostAnesthesiaSheet.css';
import chartPlaceholderSrc from './img/post anesthesia sheet.png';

const chartSectionStyle = {
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  marginBottom: '2mm',
};

const chartImageStyle = {
  width: '190mm',
  height: '180mm',
  display: 'block',
  objectFit: 'fill',
};

const PostAnesthesiaSheet = ({ patientName, patientData }) => {
  const name = patientName || "FELISELDA , CIAN REIN BAYSA";
  const caseNo = patientData?.caseNo || "ADM-2026-010651";
  const hospitalNo = patientData?.hospitalNo || "000000000021041";

  const generatedOn = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const timeStr = now.toLocaleTimeString("en-US", {
      hour: "2-digit", minute: "2-digit", hour12: true,
    }).toLowerCase();
    return `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${timeStr}`;
  }, []);

  const generatedBy = "TCP T. TCP";

  return (
    <div className="neuro-vital-signs-container">
      <div className="neuro-vital-signs">
        <section className="form-intro pacu-header" aria-label="Form title and patient details">
          <div className="pacu-panel">
            <div className="pacu-row pacu-row--top">
              <div className="pacu-cell">
                <span className="pacu-label">Hospital No.:</span>
                <span className="pacu-value">{hospitalNo}</span>
              </div>
              <div className="pacu-cell pacu-cell--center">
                <span className="pacu-label">Case Number:</span>
                <span className="pacu-value">{caseNo}</span>
              </div>
              <div className="pacu-cell pacu-cell--right"></div>
            </div>

            <div className="pacu-row pacu-row--patient">
              <div className="pacu-cell">
                <span className="pacu-label">NAME:</span>
                <span className="pacu-value">{name}</span>
              </div>
              <div className="pacu-cell pacu-cell--center">
                <span className="pacu-label">DATE:</span>
              </div>
              <div className="pacu-cell pacu-cell--center">
                <span className="pacu-check">[ ] CHARITY</span>
              </div>
            </div>

            <div className="pacu-row pacu-row--procedure">
              <div className="pacu-cell">
                <span className="pacu-label">PROCEDURE</span>
              </div>
              <div className="pacu-cell pacu-cell--center">
                <span className="pacu-label">TIME:</span>
              </div>
              <div className="pacu-cell pacu-cell--center">
                <span className="pacu-check">[ ] PHIC</span>
              </div>
            </div>

            <div className="pacu-row pacu-row--surgeon">
              <div className="pacu-cell">
                <span className="pacu-label">SURGEON/S:</span>
              </div>
              <div className="pacu-cell">
                <span className="pacu-label">Blood Transfusion Site:</span>
              </div>
            </div>

            <div className="pacu-row pacu-row--anesthesia">
              <div className="pacu-cell">
                <span className="pacu-label">ANESTHESIOLOGIST/S:</span>
              </div>
              <div className="pacu-cell pacu-cell--center">
                <span className="pacu-label">Component:</span>
              </div>
              <div className="pacu-cell pacu-cell--center">
                <span className="pacu-label">Blood Type:</span>
              </div>
              <div className="pacu-cell pacu-cell--center">
                <span className="pacu-label">Serial #:</span>
              </div>
            </div>
          </div>
        </section>

        <section aria-label="Post-Anesthesia Sheet chart image" style={chartSectionStyle}>
          <img
            src={chartPlaceholderSrc}
            alt="Post-Anesthesia Sheet status chart placeholder"
            style={chartImageStyle}
          />
        </section>
        <div className="form-footer">Generated by: {generatedBy} on {generatedOn}</div>
      </div>
    </div>
  );
};

export default PostAnesthesiaSheet;