import { useMemo } from "react";
import "./RadiologyRequestOutside.css";

export default function RadiologyRequestOutside({ patientName, patientData }) {
  const name        = patientName              || "SALUCANA , NELLY JEAN LOFRANCO";
  const age         = patientData?.age         || "32 year(s)";
  const sex         = patientData?.sex         || "F";
  const civilStatus = patientData?.civilStatus || "M";
  const birthdate   = patientData?.birthdate   || "July 27, 1993";
  const address     = patientData?.address     || "P-1E, AMPAYON, BUTUAN CITY (Capital), AGUSAN DEL NORTE";
  const ward        = patientData?.ward        || "OB GYNE - POST-OP OB - BED 07";
  const caseNo      = patientData?.caseNo      || "ADM-2026-010707";
  const category    = patientData?.category    || "OBSTETRICS";

  const { dateStr, generatedOn } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const h = now.getHours();
    const m = now.getMinutes();
    const ampm = h >= 12 ? "pm" : "am";
    const hh = String(h % 12 || 12).padStart(2, "0");
    const dateStr = now.toLocaleDateString("en-US", {
      year: "numeric", month: "long", day: "numeric",
    });
    const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(m)} ${ampm}`;
    return { dateStr, generatedOn };
  }, []);

  return (
    <div className="rro-page">
      <br />
      <div className="rro-date-row">
        <strong>Date ordered:</strong> {dateStr}
      </div>
      {/* ── Patient details ── */}
      <div className="rro-patient-grid">
        <div className="rro-patient-row">
          <div className="rro-field">
            <span className="rro-lbl">Name of the Patient:</span>
            <span className="rro-val">{name}</span>
          </div>
          <div className="rro-field rro-field-right">
            <span className="rro-lbl">Sex:</span>
            <span className="rro-val">{sex}</span>
          </div>
        </div>

        <div className="rro-patient-row">
          <div className="rro-field">
            <span className="rro-lbl">Address:</span>
            <span className="rro-val">{address}</span>
          </div>
          <div className="rro-field rro-field-right">
            <span className="rro-lbl">Civil Status:</span>
            <span className="rro-val">{civilStatus}</span>
          </div>
        </div>

        <div className="rro-patient-row">
          <div className="rro-field">
            <span className="rro-lbl">Ward:</span>
            <span className="rro-val">{ward}</span>
          </div>
          <div className="rro-field rro-field-right">
            <span className="rro-lbl">Birthdate:</span>
            <span className="rro-val">{birthdate}</span>
          </div>
        </div>

        <div className="rro-patient-row">
          <div className="rro-field">
            <span className="rro-lbl">Case Number:</span>
            <span className="rro-val">{caseNo}</span>
          </div>
          <div className="rro-field rro-field-right">
            <span className="rro-lbl">Category:</span>
            <span className="rro-val">{category}</span>
          </div>
        </div>
      </div>

      {/* ── Age row ── */}
      <div className="rro-age-row">
        <span className="rro-lbl">Age:</span>
        <span className="rro-val">{age}</span>
      </div>

      {/* ── History of Present Illness ── */}
      <div className="rro-history-label">History of Present Illness:</div>

      <hr className="rro-divider" />

      {/* ── Title ── */}
      <div className="rro-title">X-RAY/ULTRASONOGRAPHY REQUEST</div>

      <hr className="rro-divider" />

      {/* ── Blank request lines ── */}
      <div className="rro-blank-line" />
      <div className="rro-blank-line" />
      <div className="rro-blank-line" />

      {/* ── Signature row ── */}
      <div className="rro-sig-row">
        <div className="rro-sig-left">
          <span className="rro-sig-line-left" />
          <span className="rro-sig-suffix">,M.D.</span>
        </div>
        <span className="rro-sig-line-right" />
      </div>

      {/* ── Sig labels ── */}
      <div className="rro-sig-labels-row">
        <div className="rro-sig-label-left">Requesting Physician</div>
        <div className="rro-sig-label-right">Rad. Tech on duty</div>
      </div>

      {/* ── Footer ── */}
      <div className="rro-footer">
        Generated by: TCP T. TCP on {generatedOn}
      </div>

    </div>
  );
}