import { useMemo } from "react";
import "./RefusalToTreatment.css";

export default function RefusalToTreatment({ patientName, patientData }) {
	const name = patientName || "BAYSA , BABY BOY";

	const { dateTimeStr, generatedOn } = useMemo(() => {
		const now = new Date();
		const pad = (n) => String(n).padStart(2, "0");
		const h = now.getHours();
		const m = now.getMinutes();
		const ampm = h >= 12 ? "AM" : "AM";
		const hh = String(h % 12 || 12).padStart(2, "0");
		const timeStr = `${hh}:${pad(m)} ${ampm}`;
		const dateStr = now.toLocaleDateString("en-US", {
			year: "numeric", month: "long", day: "numeric",
		});
		const dateTimeStr = `${dateStr} ${timeStr}`;
		const ampmLower = ampm.toLowerCase();
		const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(m)} ${ampmLower}`;
		return { dateTimeStr, generatedOn };
	}, []);

	return (
		<div className="rtt-page">

			{/* ── Opening paragraph ── */}
			<p className="rtt-opening">
				I,&nbsp;
				<span className="rtt-line" style={{ width: "220px" }} />
				, of legal age,married/single/widowed, hereby expressly REFUSE TO CONSENT, under any circumstance to {name} the hereunder treatment/procedures:
			</p>

			{/* ── Numbered list of 4 blank lines ── */}
			<div className="rtt-numbered-list">
				{[1, 2, 3, 4].map((n) => (
					<div key={n} className="rtt-numbered-item">
						<span className="rtt-num">{n}.</span>
						<span className="rtt-item-line" />
					</div>
				))}
			</div>

			{/* ── Release paragraph ── */}
			<p className="rtt-release">
				I release the Agusan del Norte Provincial Hospital, attending physicians, and hospital staff for any damages or any untoward effects in any way arising out, or connected with my refusal to treatment/procedure.
			</p>

			{/* ── Signature row 1 ── */}
			{/* Left: sig line + label | Right: sig line + label */}
			<div className="rtt-sig-row">
				<div className="rtt-sig-block">
					<div className="rtt-sig-line" />
					<p className="rtt-sig-label">Signature over printed name of person causing the refusal</p>
				</div>
				<div className="rtt-sig-block">
					<div className="rtt-sig-line" />
					<p className="rtt-sig-label">Signature over printed name of physician/nurse on duty</p>
				</div>
			</div>

			{/* ── Signature row 2 ── */}
			{/* Left: sig line + "Relation to patient" | Right: datetime text + "Date and Time signed" */}
			<div className="rtt-sig-row">
				<div className="rtt-sig-block">
					<div className="rtt-sig-line" />
					<p className="rtt-sig-label">Relation to patient</p>
				</div>
				<div className="rtt-sig-block">
					<p className="rtt-datetime">{dateTimeStr}</p>
					<p className="rtt-sig-label">Date and Time signed</p>
				</div>
			</div>

			{/* ── Footer ── */}
			<div className="rtt-footer">
				Generated by: TCP T. TCP on {generatedOn}
			</div>

		</div>
	);
}