import { useMemo } from "react";
import "./SpecialEndorsement.css";

export default function SpecialEndorsement({ patientName, patientData }) {
  const hospitalNumber = patientData?.hospitalNumber || "000000000021041";
  const caseNumber     = patientData?.caseNumber     || "ADM-2026-010651";
  const name           = patientName                 || "BAYSA , BABY BOY";
  const dateOfBirth    = patientData?.dateOfBirth    || "04:10 AM";

  const { generatedOn } = useMemo(() => {
    const now  = new Date();
    const pad  = (n) => String(n).padStart(2, "0");
    const h    = now.getHours();
    const hh   = String(h % 12 || 12).padStart(2, "0");
    const ampm = h < 12 ? "am" : "pm";
    return {
      generatedOn: `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(now.getMinutes())} ${ampm}`,
    };
  }, []);

  const ITEMS = [
    "VIT. K",
    "HEP. B",
    "BCG",
    "HEARING TEST",
    "BLOOD GSCS",
    "CBC, PC, BT",
    "CRP",
    "CXR-APL",
    "BABY GRAM",
    "CUTZ",
    "WHOLE ABD. UTZ",
    "NBS",
    "RPT. NBS",
    "CBG/HGT",
  ];

  return (
    <div className="se-page">

      {/* ── Header ── */}
      <div className="se-header">
        <div className="se-header-left">
          <div className="se-header-row">
            <strong>Hospital No.:</strong>&nbsp;{hospitalNumber}&nbsp;&nbsp;
            <strong>Case Number:</strong>&nbsp;{caseNumber}
          </div>
          <div className="se-header-row">
            <strong>NAME:</strong>&nbsp;{name}
          </div>
        </div>
        <div className="se-header-right">
          <div><strong>DATE OF BIRTH:</strong>&nbsp;{dateOfBirth}</div>
        </div>
      </div>

      {/* ── Table ── */}
      <table className="se-table">
        <thead>
          <tr>
            <th className="se-col-diag">DIAGNOSTICS &amp; LABS</th>
            <th className="se-col-date">DATE DONE</th>
            <th className="se-col-remarks">REMARKS</th>
          </tr>
        </thead>
        <tbody>
          {ITEMS.map((item, i) => (
            <tr key={i}>
              <td className="se-item-cell">{item}</td>
              <td></td>
              <td></td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* ── Others ── */}
      <div className="se-others"><strong>OTHERS:</strong></div>

      {/* ── Footer ── */}
      <div className="se-footer">
        Generated by: TCP T. TCP on {generatedOn}
      </div>

    </div>
  );
}