import { useMemo } from "react";
import "./TPRSheet.css";

export default function TPRSheet({ patientName, patientData }) {
  const chartSrc = "src/modules/forms/img/tpr.png";

  const hospitalNumber = patientData?.hospitalNumber;
  const caseNumber     = patientData?.caseNumber;
  const name           = patientName;
  const sex            = patientData?.sex;
  const age            = patientData?.age;
  const ward           = patientData?.ward;

  const { generatedOn } = useMemo(() => {
    const now  = new Date();
    const pad  = (n) => String(n).padStart(2, "0");
    const h    = now.getHours();
    const hh   = String(h % 12 || 12).padStart(2, "0");
    const ampm = h < 12 ? "am" : "pm";
    return {
      generatedOn: `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(now.getMinutes())} ${ampm}`,
    };
  }, []);

  return (
    <div className="tpr-page">
      <br />
      <div className="tpr-chart-wrap">
        <img
          className="tpr-chart"
          src={chartSrc}
          alt="TPR Sheet"
        />
      </div>

      {/* ── Patient Info Block ── */}
      <div className="tpr-info-block">
        <div><strong>Hospital No.:</strong> {hospitalNumber}&nbsp;&nbsp;<strong>Case Number:</strong> {caseNumber}</div>
        <div><strong>Patient Name:</strong> {name}</div>
        <div><strong>Sex:</strong> {sex}</div>
        <div><strong>Age:</strong> {age}</div>
        <div><strong>Ward:</strong> {ward}</div>
      </div>

      {/* ── Footer ── */}
      <div className="tpr-footer">
        <div className="tpr-footer-line" />
        <div className="tpr-footer-text">Generated by: TCP T. TCP on {generatedOn}</div>
      </div>

    </div>
  );
}