import { useMemo } from "react";
import "./WardPreference.css";

export default function WardPreference({ patientName, patientData }) {
  const name = patientName || "BAYSA , BABY BOY";

  const { dateStr, generatedOn } = useMemo(() => {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const h = now.getHours();
    const m = now.getMinutes();
    const hh = String(h % 12 || 12).padStart(2, "0");
    const ampm = "am";
    const dateStr = now.toLocaleDateString("en-US", {
      year: "numeric", month: "long", day: "numeric",
    });
    const generatedOn = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${hh}:${pad(m)} ${ampm}`;
    return { dateStr, generatedOn };
  }, []);

  const rooms = [
    { label: "[ ] Ward without CR and without aircon",     price: "P 800.00"   },
    { label: "[ ] Semi Private Room with CR and with Aircon", price: "P 1,500.00" },
    { label: "[ ] Private Room with CR and Aircon",        price: "P 2,500.00" },
    { label: "[ ] Suite Room",                             price: "P 3,750.00" },
  ];

  return (
    <div className="wp-page">

      {/* ── Top row ── */}
      <div className="wp-top-row">
        <div className="wp-to-whom">TO WHOM IT MAY CONCERN:</div>
        <div className="wp-date">DATE:{dateStr}</div>
      </div>

      {/* ── THIS IS TO CERTIFY THAT __ voluntarily submit ── */}
      <div className="wp-certify-row">
        <span>THIS IS TO CERTIFY THAT</span>
        <span className="wp-inline-line" />
        <span>voluntarily submit</span>
      </div>

      {/* ── (Name of Requisitioning Person) ── */}
      <div className="wp-req-label">(Name of Requisitioning Person)</div>

      {/* ── Myself/my patient ── */}
      <div className="wp-myself-row">
        Myself/my patient {name} for admission at:
      </div>

      {/* ── Rooms ── */}
      <div className="wp-rooms-label">Rooms:</div>
      {rooms.map((room, i) => (
        <div key={i} className="wp-room-row">
          <span className="wp-room-name">{room.label}</span>
          <span className="wp-room-line" />
          <span className="wp-room-price">{room.price}</span>
        </div>
      ))}

      {/* ── Policy paragraph ── */}
      <p className="wp-policy">
        I/We hereby abide by the policies and guidelines of the institution including payments of bills incurred during the confinement period.
      </p>

      {/* ── Signature Over Printed Name (right-aligned) ── */}
      <br />
      <br />
      <div className="wp-sig-right">
        <div className="wp-sig-block-right">
          <div className="wp-sig-line" />
          <div className="wp-sig-label">Signature Over Printed Name</div>
        </div>
      </div>

      {/* ── Witness ── */}
      <div className="wp-witness-section">
        <div className="wp-witness-label">Witness:</div>
        <br />
        <br />
        <div className="wp-sig-block-left">
          <div className="wp-sig-line" />
          <div className="wp-sig-label-left">Signature of Admitting Clerk/ER Staff</div>
        </div>
      </div>

      {/* ── Footer ── */}
      <div className="wp-footer">
        Generated by: TCP T. TCP on {generatedOn}
      </div>

    </div>
  );
}