import { useMemo } from 'react';
import PropTypes from 'prop-types';
import './FormFooter.css';

export default function FormFooter({
  generatedBy = null,
  generatedOn = null,
  className = '',
  mode = 'flex'
}) {
  const formattedDate = useMemo(() => {
    const date = generatedOn || new Date();
    const options = {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      hour12: true
    };
    return new Intl.DateTimeFormat('en-US', options).format(date);
  }, [generatedOn]);

  const author = generatedBy || 'Generated by Unknown';
  const modeClass = mode === 'absolute-print'
    ? 'form-footer--absolute-print'
    : '';

  return (
    <footer
      className={`form-footer ${modeClass} ${className}`.trim()}
      role="contentinfo"
    >
      Generated by: {author} on {formattedDate}
    </footer>
  );
}

FormFooter.propTypes = {
  generatedBy: PropTypes.string,
  generatedOn: PropTypes.instanceOf(Date),
  className: PropTypes.string,
  mode: PropTypes.oneOf(['flex', 'absolute-print']),
};
